In [1]:
import findspark
findspark.init()

In [2]:
import pyspark
from pyspark.sql import SQLContext,SparkSession

In [3]:
spark=SparkSession.builder.appName('practice').getOrCreate()

In [4]:
spark

<h3>Lab4</h3>

In [5]:
# Word count

text=spark.sparkContext.textFile('lab3.txt')

In [6]:
text.collect()

["Big Data refers to a massive set of data that no conventional data management tool can handle. Big Data is therefore a concept that allows access to gigantic databases in real time. Big Data's main objectives are to improve a company's or system's responsiveness to a large amount of data collected, increase productivity and refine knowledge of customer behavior, so that it can offer personalized offers or advertisements and create new trends.",
 'The Internet of Things (IoT) is a concept that connects physical or virtual objects to the internet. The technology very often used is the sensor, allowing to link a physical object such as a watch, a drone or even a speaker, to the internet. If for a long time the few objects connected to the Internet were the telephone and the computer, this is no longer the case today and every year new types of objects incorporating IOT technology are born. IOT is one of the greatest technological revolutions of our era and its potential for exploitation is immense. IOT could have a huge impact on the cars of the future or on the new versions of smart-cities, an urban space connected to the Internet, thus significantly improving the lives of users, while reducing the negative impact of these on the planet. ']

In [16]:
text=text.flatMap(lambda word: word.split(' ')).map(lambda x:(x,1)).reduceByKey(lambda x,y:x+y)

In [17]:
text.collect()

[('refers', 1),
 ('massive', 1),
 ('set', 1),
 ('of', 11),
 ('no', 2),
 ('conventional', 1),
 ('management', 1),
 ('is', 6),
 ('in', 1),
 ("Data's", 1),
 ('objectives', 1),
 ('are', 2),
 ('improve', 1),
 ("company's", 1),
 ("system's", 1),
 ('large', 1),
 ('amount', 1),
 ('collected,', 1),
 ('increase', 1),
 ('knowledge', 1),
 ('customer', 1),
 ('personalized', 1),
 ('offers', 1),
 ('new', 3),
 ('The', 2),
 ('Things', 1),
 ('(IoT)', 1),
 ('connects', 1),
 ('internet.', 2),
 ('technology', 2),
 ('very', 1),
 ('used', 1),
 ('sensor,', 1),
 ('allowing', 1),
 ('as', 1),
 ('watch,', 1),
 ('even', 1),
 ('speaker,', 1),
 ('long', 1),
 ('telephone', 1),
 ('computer,', 1),
 ('this', 1),
 ('longer', 1),
 ('year', 1),
 ('incorporating', 1),
 ('IOT', 3),
 ('born.', 1),
 ('greatest', 1),
 ('potential', 1),
 ('exploitation', 1),
 ('have', 1),
 ('huge', 1),
 ('versions', 1),
 ('an', 1),
 ('space', 1),
 ('Internet,', 1),
 ('thus', 1),
 ('significantly', 1),
 ('reducing', 1),
 ('negative', 1),
 ('these', 1),
 ('planet.', 1),
 ('', 1),
 ('Big', 3),
 ('Data', 2),
 ('to', 9),
 ('a', 11),
 ('data', 3),
 ('that', 4),
 ('tool', 1),
 ('can', 2),
 ('handle.', 1),
 ('therefore', 1),
 ('concept', 2),
 ('allows', 1),
 ('access', 1),
 ('gigantic', 1),
 ('databases', 1),
 ('real', 1),
 ('time.', 1),
 ('main', 1),
 ('or', 5),
 ('responsiveness', 1),
 ('productivity', 1),
 ('and', 5),
 ('refine', 1),
 ('behavior,', 1),
 ('so', 1),
 ('it', 1),
 ('offer', 1),
 ('advertisements', 1),
 ('create', 1),
 ('trends.', 1),
 ('Internet', 2),
 ('physical', 2),
 ('virtual', 1),
 ('objects', 3),
 ('the', 16),
 ('often', 1),
 ('link', 1),
 ('object', 1),
 ('such', 1),
 ('drone', 1),
 ('If', 1),
 ('for', 2),
 ('time', 1),
 ('few', 1),
 ('connected', 2),
 ('were', 1),
 ('case', 1),
 ('today', 1),
 ('every', 1),
 ('types', 1),
 ('one', 1),
 ('technological', 1),
 ('revolutions', 1),
 ('our', 1),
 ('era', 1),
 ('its', 1),
 ('immense.', 1),
 ('could', 1),
 ('impact', 2),
 ('on', 3),
 ('cars', 1),
 ('future', 1),
 ('smart-cities,', 1),
 ('urban', 1),
 ('improving', 1),
 ('lives', 1),
 ('users,', 1),
 ('while', 1)]

In [ ]:
text.saveAsTextFile('lab')

<h3>Database task</h3>

In [20]:
#case file
case=spark.read.load('case.csv',format='csv',inferSchema=True,header=True)
case.show()

+--------+--------+---------------+-----+--------------------+---------+---------+----------+
| case_id|province|           city|group|      infection_case|confirmed| latitude| longitude|
+--------+--------+---------------+-----+--------------------+---------+---------+----------+
| 1000001|   Seoul|     Yongsan-gu| true|       Itaewon Clubs|      139|37.538621|126.992652|
| 1000002|   Seoul|      Gwanak-gu| true|             Richway|      119| 37.48208|126.901384|
| 1000003|   Seoul|        Guro-gu| true| Guro-gu Call Center|       95|37.508163|126.884387|
| 1000004|   Seoul|   Yangcheon-gu| true|Yangcheon Table T...|       43|37.546061|126.874209|
| 1000005|   Seoul|      Dobong-gu| true|     Day Care Center|       43|37.679422|127.044374|
| 1000006|   Seoul|        Guro-gu| true|Manmin Central Ch...|       41|37.481059|126.894343|
| 1000007|   Seoul|from other city| true|SMR Newly Planted...|       36|        -|         -|
| 1000008|   Seoul|  Dongdaemun-gu| true|       Dongan Church|       17|37.592888|127.056766|
| 1000009|   Seoul|from other city| true|Coupang Logistics...|       25|        -|         -|
| 1000010|   Seoul|      Gwanak-gu| true|     Wangsung Church|       30|37.481735|126.930121|
| 1000011|   Seoul|   Eunpyeong-gu| true|Eunpyeong St. Mar...|       14| 37.63369|  126.9165|
| 1000012|   Seoul|   Seongdong-gu| true|    Seongdong-gu APT|       13| 37.55713|  127.0403|
| 1000013|   Seoul|      Jongno-gu| true|Jongno Community ...|       10| 37.57681|   127.006|
| 1000014|   Seoul|     Gangnam-gu| true|Samsung Medical C...|        7| 37.48825| 127.08559|
| 1000015|   Seoul|        Jung-gu| true|Jung-gu Fashion C...|        7|37.562405|126.984377|
| 1000016|   Seoul|   Seodaemun-gu| true|  Yeonana News Class|        5|37.558147|126.943799|
| 1000017|   Seoul|      Jongno-gu| true|Korea Campus Crus...|        7|37.594782|126.968022|
| 1000018|   Seoul|     Gangnam-gu| true|Gangnam Yeoksam-d...|        6|        -|         -|
| 1000019|   Seoul|from other city| true|Daejeon door-to-d...|        1|        -|         -|
| 1000020|   Seoul|   Geumcheon-gu| true|Geumcheon-gu rice...|        6|        -|         -|
+--------+--------+---------------+-----+--------------------+---------+---------+----------+
only showing top 20 rows

In [21]:
case.printSchema()

root
 |--  case_id: integer (nullable = true)
 |-- province: string (nullable = true)
 |-- city: string (nullable = true)
 |-- group: boolean (nullable = true)
 |-- infection_case: string (nullable = true)
 |-- confirmed: integer (nullable = true)
 |-- latitude: string (nullable = true)
 |-- longitude: string (nullable = true)

In [22]:
case.limit(10).toPandas()

,case_id,province,city,group,infection_case,confirmed,latitude,longitude
0,1000001,Seoul,Yongsan-gu,True,Itaewon Clubs,139,37.538621,126.992652
1,1000002,Seoul,Gwanak-gu,True,Richway,119,37.48208,126.901384
2,1000003,Seoul,Guro-gu,True,Guro-gu Call Center,95,37.508163,126.884387
3,1000004,Seoul,Yangcheon-gu,True,Yangcheon Table Tennis Club,43,37.546061,126.874209
4,1000005,Seoul,Dobong-gu,True,Day Care Center,43,37.679422,127.044374
5,1000006,Seoul,Guro-gu,True,Manmin Central Church,41,37.481059,126.894343
6,1000007,Seoul,from other city,True,SMR Newly Planted Churches Group,36,-,-
7,1000008,Seoul,Dongdaemun-gu,True,Dongan Church,17,37.592888,127.056766
8,1000009,Seoul,from other city,True,Coupang Logistics Center,25,-,-
9,1000010,Seoul,Gwanak-gu,True,Wangsung Church,30,37.481735,126.930121

In [23]:
case=case.withColumnRenamed('infection_case','infection_source')

In [24]:
case.show()

+--------+--------+---------------+-----+--------------------+---------+---------+----------+
| case_id|province|           city|group|    infection_source|confirmed| latitude| longitude|
+--------+--------+---------------+-----+--------------------+---------+---------+----------+
| 1000001|   Seoul|     Yongsan-gu| true|       Itaewon Clubs|      139|37.538621|126.992652|
| 1000002|   Seoul|      Gwanak-gu| true|             Richway|      119| 37.48208|126.901384|
| 1000003|   Seoul|        Guro-gu| true| Guro-gu Call Center|       95|37.508163|126.884387|
| 1000004|   Seoul|   Yangcheon-gu| true|Yangcheon Table T...|       43|37.546061|126.874209|
| 1000005|   Seoul|      Dobong-gu| true|     Day Care Center|       43|37.679422|127.044374|
| 1000006|   Seoul|        Guro-gu| true|Manmin Central Ch...|       41|37.481059|126.894343|
| 1000007|   Seoul|from other city| true|SMR Newly Planted...|       36|        -|         -|
| 1000008|   Seoul|  Dongdaemun-gu| true|       Dongan Church|       17|37.592888|127.056766|
| 1000009|   Seoul|from other city| true|Coupang Logistics...|       25|        -|         -|
| 1000010|   Seoul|      Gwanak-gu| true|     Wangsung Church|       30|37.481735|126.930121|
| 1000011|   Seoul|   Eunpyeong-gu| true|Eunpyeong St. Mar...|       14| 37.63369|  126.9165|
| 1000012|   Seoul|   Seongdong-gu| true|    Seongdong-gu APT|       13| 37.55713|  127.0403|
| 1000013|   Seoul|      Jongno-gu| true|Jongno Community ...|       10| 37.57681|   127.006|
| 1000014|   Seoul|     Gangnam-gu| true|Samsung Medical C...|        7| 37.48825| 127.08559|
| 1000015|   Seoul|        Jung-gu| true|Jung-gu Fashion C...|        7|37.562405|126.984377|
| 1000016|   Seoul|   Seodaemun-gu| true|  Yeonana News Class|        5|37.558147|126.943799|
| 1000017|   Seoul|      Jongno-gu| true|Korea Campus Crus...|        7|37.594782|126.968022|
| 1000018|   Seoul|     Gangnam-gu| true|Gangnam Yeoksam-d...|        6|        -|         -|
| 1000019|   Seoul|from other city| true|Daejeon door-to-d...|        1|        -|         -|
| 1000020|   Seoul|   Geumcheon-gu| true|Geumcheon-gu rice...|        6|        -|         -|
+--------+--------+---------------+-----+--------------------+---------+---------+----------+
only showing top 20 rows

In [27]:
case=case.toDF(*['case_id','province','city','group','infection_case','confirmed', 'latitude','longitude'])

In [28]:
case.show()

+-------+--------+---------------+-----+--------------------+---------+---------+----------+
|case_id|province|           city|group|      infection_case|confirmed| latitude| longitude|
+-------+--------+---------------+-----+--------------------+---------+---------+----------+
|1000001|   Seoul|     Yongsan-gu| true|       Itaewon Clubs|      139|37.538621|126.992652|
|1000002|   Seoul|      Gwanak-gu| true|             Richway|      119| 37.48208|126.901384|
|1000003|   Seoul|        Guro-gu| true| Guro-gu Call Center|       95|37.508163|126.884387|
|1000004|   Seoul|   Yangcheon-gu| true|Yangcheon Table T...|       43|37.546061|126.874209|
|1000005|   Seoul|      Dobong-gu| true|     Day Care Center|       43|37.679422|127.044374|
|1000006|   Seoul|        Guro-gu| true|Manmin Central Ch...|       41|37.481059|126.894343|
|1000007|   Seoul|from other city| true|SMR Newly Planted...|       36|        -|         -|
|1000008|   Seoul|  Dongdaemun-gu| true|       Dongan Church|       17|37.592888|127.056766|
|1000009|   Seoul|from other city| true|Coupang Logistics...|       25|        -|         -|
|1000010|   Seoul|      Gwanak-gu| true|     Wangsung Church|       30|37.481735|126.930121|
|1000011|   Seoul|   Eunpyeong-gu| true|Eunpyeong St. Mar...|       14| 37.63369|  126.9165|
|1000012|   Seoul|   Seongdong-gu| true|    Seongdong-gu APT|       13| 37.55713|  127.0403|
|1000013|   Seoul|      Jongno-gu| true|Jongno Community ...|       10| 37.57681|   127.006|
|1000014|   Seoul|     Gangnam-gu| true|Samsung Medical C...|        7| 37.48825| 127.08559|
|1000015|   Seoul|        Jung-gu| true|Jung-gu Fashion C...|        7|37.562405|126.984377|
|1000016|   Seoul|   Seodaemun-gu| true|  Yeonana News Class|        5|37.558147|126.943799|
|1000017|   Seoul|      Jongno-gu| true|Korea Campus Crus...|        7|37.594782|126.968022|
|1000018|   Seoul|     Gangnam-gu| true|Gangnam Yeoksam-d...|        6|        -|         -|
|1000019|   Seoul|from other city| true|Daejeon door-to-d...|        1|        -|         -|
|1000020|   Seoul|   Geumcheon-gu| true|Geumcheon-gu rice...|        6|        -|         -|
+-------+--------+---------------+-----+--------------------+---------+---------+----------+
only showing top 20 rows

In [29]:
case=case.select('case_id','province','city','confirmed')
case.show()

+-------+--------+---------------+---------+
|case_id|province|           city|confirmed|
+-------+--------+---------------+---------+
|1000001|   Seoul|     Yongsan-gu|      139|
|1000002|   Seoul|      Gwanak-gu|      119|
|1000003|   Seoul|        Guro-gu|       95|
|1000004|   Seoul|   Yangcheon-gu|       43|
|1000005|   Seoul|      Dobong-gu|       43|
|1000006|   Seoul|        Guro-gu|       41|
|1000007|   Seoul|from other city|       36|
|1000008|   Seoul|  Dongdaemun-gu|       17|
|1000009|   Seoul|from other city|       25|
|1000010|   Seoul|      Gwanak-gu|       30|
|1000011|   Seoul|   Eunpyeong-gu|       14|
|1000012|   Seoul|   Seongdong-gu|       13|
|1000013|   Seoul|      Jongno-gu|       10|
|1000014|   Seoul|     Gangnam-gu|        7|
|1000015|   Seoul|        Jung-gu|        7|
|1000016|   Seoul|   Seodaemun-gu|        5|
|1000017|   Seoul|      Jongno-gu|        7|
|1000018|   Seoul|     Gangnam-gu|        6|
|1000019|   Seoul|from other city|        1|
|1000020|   Seoul|   Geumcheon-gu|        6|
+-------+--------+---------------+---------+
only showing top 20 rows

In [30]:
case.sort('confirmed').show()

+-------+-----------------+---------------+---------+
|case_id|         province|           city|confirmed|
+-------+-----------------+---------------+---------+
|7000002|          Jeju-do|              -|        0|
|3000007|       Gangwon-do|              -|        0|
|1000030|            Seoul|     Gangseo-gu|        0|
|1100007|            Busan|from other city|        1|
|5000003|     Jeollabuk-do|from other city|        1|
|1000028|            Seoul|from other city|        1|
|1000025|            Seoul|     Gangnam-gu|        1|
|1700003|           Sejong|from other city|        1|
|5100002|     Jeollanam-do|from other city|        1|
|7000004|          Jeju-do|from other city|        1|
|1000019|            Seoul|from other city|        1|
|1000034|            Seoul|              -|        1|
|1700006|           Sejong|              -|        1|
|1300005|          Gwangju|              -|        1|
|1200006|            Daegu|from other city|        2|
|1200007|            Daegu|from other city|        2|
|1400004|          Incheon|from other city|        2|
|1000033|            Seoul|from other city|        2|
|1500006|          Daejeon|from other city|        2|
|4000003|Chungcheongbuk-do|from other city|        2|
+-------+-----------------+---------------+---------+
only showing top 20 rows

In [31]:
from pyspark.sql import functions as F
case.sort(F.desc('confirmed')).show()

+-------+-----------------+---------------+---------+
|case_id|         province|           city|confirmed|
+-------+-----------------+---------------+---------+
|1200001|            Daegu|         Nam-gu|     4511|
|1200009|            Daegu|              -|      917|
|1200010|            Daegu|              -|      747|
|6000001| Gyeongsangbuk-do|from other city|      566|
|2000020|      Gyeonggi-do|              -|      305|
|1000036|            Seoul|              -|      298|
|1200002|            Daegu|   Dalseong-gun|      196|
|6000012| Gyeongsangbuk-do|              -|      190|
|1000037|            Seoul|              -|      162|
|1000001|            Seoul|     Yongsan-gu|      139|
|6000013| Gyeongsangbuk-do|              -|      133|
|1200003|            Daegu|         Seo-gu|      124|
|1000002|            Seoul|      Gwanak-gu|      119|
|6000002| Gyeongsangbuk-do|   Cheongdo-gun|      119|
|4100001|Chungcheongnam-do|     Cheonan-si|      103|
|1200004|            Daegu|   Dalseong-gun|      101|
|1000038|            Seoul|              -|      100|
|1000003|            Seoul|        Guro-gu|       95|
|2000022|      Gyeonggi-do|              -|       84|
|1400005|          Incheon|              -|       68|
+-------+-----------------+---------------+---------+
only showing top 20 rows

In [32]:
from pyspark.sql.types import *
cases=case.withColumn('confirmed',F.col('confirmed').cast(IntegerType()))

In [33]:
cases.show()

+-------+--------+---------------+---------+
|case_id|province|           city|confirmed|
+-------+--------+---------------+---------+
|1000001|   Seoul|     Yongsan-gu|      139|
|1000002|   Seoul|      Gwanak-gu|      119|
|1000003|   Seoul|        Guro-gu|       95|
|1000004|   Seoul|   Yangcheon-gu|       43|
|1000005|   Seoul|      Dobong-gu|       43|
|1000006|   Seoul|        Guro-gu|       41|
|1000007|   Seoul|from other city|       36|
|1000008|   Seoul|  Dongdaemun-gu|       17|
|1000009|   Seoul|from other city|       25|
|1000010|   Seoul|      Gwanak-gu|       30|
|1000011|   Seoul|   Eunpyeong-gu|       14|
|1000012|   Seoul|   Seongdong-gu|       13|
|1000013|   Seoul|      Jongno-gu|       10|
|1000014|   Seoul|     Gangnam-gu|        7|
|1000015|   Seoul|        Jung-gu|        7|
|1000016|   Seoul|   Seodaemun-gu|        5|
|1000017|   Seoul|      Jongno-gu|        7|
|1000018|   Seoul|     Gangnam-gu|        6|
|1000019|   Seoul|from other city|        1|
|1000020|   Seoul|   Geumcheon-gu|        6|
+-------+--------+---------------+---------+
only showing top 20 rows

In [34]:
cases.filter(cases.confirmed>100).show()

+-------+-----------------+---------------+---------+
|case_id|         province|           city|confirmed|
+-------+-----------------+---------------+---------+
|1000001|            Seoul|     Yongsan-gu|      139|
|1000002|            Seoul|      Gwanak-gu|      119|
|1000036|            Seoul|              -|      298|
|1000037|            Seoul|              -|      162|
|1200001|            Daegu|         Nam-gu|     4511|
|1200002|            Daegu|   Dalseong-gun|      196|
|1200003|            Daegu|         Seo-gu|      124|
|1200004|            Daegu|   Dalseong-gun|      101|
|1200009|            Daegu|              -|      917|
|1200010|            Daegu|              -|      747|
|2000020|      Gyeonggi-do|              -|      305|
|4100001|Chungcheongnam-do|     Cheonan-si|      103|
|6000001| Gyeongsangbuk-do|from other city|      566|
|6000002| Gyeongsangbuk-do|   Cheongdo-gun|      119|
|6000012| Gyeongsangbuk-do|              -|      190|
|6000013| Gyeongsangbuk-do|              -|      133|
+-------+-----------------+---------------+---------+

In [37]:
cases.filter((cases.confirmed>100) & (cases.city=='Nam-gu')).show()

+-------+--------+------+---------+
|case_id|province|  city|confirmed|
+-------+--------+------+---------+
|1200001|   Daegu|Nam-gu|     4511|
+-------+--------+------+---------+

In [40]:
cases.groupBy(['province','city']).agg(F.sum('confirmed').alias("Total confirmed"),F.max('confirmed').alias('Max')).show()

+----------------+---------------+---------------+---+
|        province|           city|Total confirmed|Max|
+----------------+---------------+---------------+---+
|Gyeongsangnam-do|       Jinju-si|              9|  9|
|           Seoul|        Guro-gu|            139| 95|
|           Seoul|     Gangnam-gu|             18|  7|
|         Daejeon|              -|            100| 55|
|    Jeollabuk-do|from other city|              6|  3|
|Gyeongsangnam-do|Changnyeong-gun|              7|  7|
|           Seoul|              -|            561|298|
|         Jeju-do|from other city|              1|  1|
|Gyeongsangbuk-do|              -|            345|190|
|Gyeongsangnam-do|   Geochang-gun|             18| 10|
|Gyeongsangbuk-do|        Gumi-si|             10| 10|
|         Incheon|from other city|            117| 53|
|           Busan|              -|             85| 36|
|           Daegu|         Seo-gu|            124|124|
|           Busan|     Suyeong-gu|              5|  5|
|     Gyeonggi-do|   Uijeongbu-si|             50| 50|
|           Seoul|     Yongsan-gu|            139|139|
|           Daegu|              -|           1705|917|
|           Seoul|   Seodaemun-gu|              5|  5|
|     Gyeonggi-do|    Seongnam-si|             94| 67|
+----------------+---------------+---------------+---+
only showing top 20 rows

In [42]:
cases.withColumn('New confirmed',100+F.col('confirmed')).show()

+-------+--------+---------------+---------+-------------+
|case_id|province|           city|confirmed|New confirmed|
+-------+--------+---------------+---------+-------------+
|1000001|   Seoul|     Yongsan-gu|      139|          239|
|1000002|   Seoul|      Gwanak-gu|      119|          219|
|1000003|   Seoul|        Guro-gu|       95|          195|
|1000004|   Seoul|   Yangcheon-gu|       43|          143|
|1000005|   Seoul|      Dobong-gu|       43|          143|
|1000006|   Seoul|        Guro-gu|       41|          141|
|1000007|   Seoul|from other city|       36|          136|
|1000008|   Seoul|  Dongdaemun-gu|       17|          117|
|1000009|   Seoul|from other city|       25|          125|
|1000010|   Seoul|      Gwanak-gu|       30|          130|
|1000011|   Seoul|   Eunpyeong-gu|       14|          114|
|1000012|   Seoul|   Seongdong-gu|       13|          113|
|1000013|   Seoul|      Jongno-gu|       10|          110|
|1000014|   Seoul|     Gangnam-gu|        7|          107|
|1000015|   Seoul|        Jung-gu|        7|          107|
|1000016|   Seoul|   Seodaemun-gu|        5|          105|
|1000017|   Seoul|      Jongno-gu|        7|          107|
|1000018|   Seoul|     Gangnam-gu|        6|          106|
|1000019|   Seoul|from other city|        1|          101|
|1000020|   Seoul|   Geumcheon-gu|        6|          106|
+-------+--------+---------------+---------+-------------+
only showing top 20 rows

In [43]:
region=spark.read.load('region.csv',format='csv',inferSchema=True,header=True)
region.show()

+-----+--------+-------------+---------+----------+-----------------------+------------------+----------------+-------------+------------------------+-------------------+------------------+
| code|province|         city| latitude| longitude|elementary_school_count|kindergarten_count|university_count|academy_ratio|elderly_population_ratio|elderly_alone_ratio|nursing_home_count|
+-----+--------+-------------+---------+----------+-----------------------+------------------+----------------+-------------+------------------------+-------------------+------------------+
|10000|   Seoul|        Seoul|37.566953|126.977977|                    607|               830|              48|         1.44|                   15.38|                5.8|             22739|
|10010|   Seoul|   Gangnam-gu|37.518421|127.047222|                     33|                38|               0|         4.18|                   13.17|                4.3|              3088|
|10020|   Seoul|  Gangdong-gu|37.530492|127.123837|                     27|                32|               0|         1.54|                   14.55|                5.4|              1023|
|10030|   Seoul|   Gangbuk-gu|37.639938|127.025508|                     14|                21|               0|         0.67|                   19.49|                8.5|               628|
|10040|   Seoul|   Gangseo-gu|37.551166|126.849506|                     36|                56|               1|         1.17|                   14.39|                5.7|              1080|
|10050|   Seoul|    Gwanak-gu| 37.47829|126.951502|                     22|                33|               1|         0.89|                   15.12|                4.9|               909|
|10060|   Seoul|  Gwangjin-gu|37.538712|127.082366|                     22|                33|               3|         1.16|                   13.75|                4.8|               723|
|10070|   Seoul|      Guro-gu|37.495632| 126.88765|                     26|                34|               3|          1.0|                   16.21|                5.7|               741|
|10080|   Seoul| Geumcheon-gu|37.456852|126.895229|                     18|                19|               0|         0.96|                   16.15|                6.7|               475|
|10090|   Seoul|     Nowon-gu|37.654259|127.056294|                     42|                66|               6|         1.39|                    15.4|                7.4|               952|
|10100|   Seoul|    Dobong-gu|37.668952|127.047082|                     23|                26|               1|         0.95|                   17.89|                7.2|               485|
|10110|   Seoul|Dongdaemun-gu|37.574552|127.039721|                     21|                31|               4|         1.06|                   17.26|                6.7|               832|
|10120|   Seoul|   Dongjak-gu|37.510571|126.963604|                     21|                34|               3|         1.17|                   15.85|                5.2|               762|
|10130|   Seoul|      Mapo-gu|37.566283|126.901644|                     22|                24|               2|         1.83|                   14.05|                4.9|               929|
|10140|   Seoul| Seodaemun-gu|37.579428|126.936771|                     19|                25|               6|         1.12|                   16.77|                6.2|               587|
|10150|   Seoul|    Seocho-gu|37.483804|127.032693|                     24|                27|               1|          2.6|                   13.39|                3.8|              1465|
|10160|   Seoul| Seongdong-gu|37.563277|127.036647|                     21|                30|               2|         0.97|                   14.76|                5.3|               593|
|10170|   Seoul|  Seongbuk-gu|37.589562|  127.0167|                     29|                49|               6|         1.02|                   16.15|                6.0|               729|
|10180|   Seoul|    Songpa-gu| 37.51462|127.106141|                     40|                51|               1|         1.65|                    13.1|                4.1|              1527|
|10190|   Seoul| Yangcheon-gu|37.517189|126.866618|                     30|                43|               0|         2.26|                   13.55|                5.5|               816|
+-----+--------+-------------+---------+----------+-----------------------+------------------+----------------+-------------+------------------------+-------------------+------------------+
only showing top 20 rows

In [44]:
cases.join(region,['province','city'],how='left').show()

+--------+---------------+-------+---------+-----+---------+----------+-----------------------+------------------+----------------+-------------+------------------------+-------------------+------------------+
|province|           city|case_id|confirmed| code| latitude| longitude|elementary_school_count|kindergarten_count|university_count|academy_ratio|elderly_population_ratio|elderly_alone_ratio|nursing_home_count|
+--------+---------------+-------+---------+-----+---------+----------+-----------------------+------------------+----------------+-------------+------------------------+-------------------+------------------+
|   Seoul|     Yongsan-gu|1000001|      139|10210|37.532768|126.990021|                     15|                13|               1|         0.68|                   16.87|                6.5|               435|
|   Seoul|      Gwanak-gu|1000002|      119|10050| 37.47829|126.951502|                     22|                33|               1|         0.89|                   15.12|                4.9|               909|
|   Seoul|        Guro-gu|1000003|       95|10070|37.495632| 126.88765|                     26|                34|               3|          1.0|                   16.21|                5.7|               741|
|   Seoul|   Yangcheon-gu|1000004|       43|10190|37.517189|126.866618|                     30|                43|               0|         2.26|                   13.55|                5.5|               816|
|   Seoul|      Dobong-gu|1000005|       43|10100|37.668952|127.047082|                     23|                26|               1|         0.95|                   17.89|                7.2|               485|
|   Seoul|        Guro-gu|1000006|       41|10070|37.495632| 126.88765|                     26|                34|               3|          1.0|                   16.21|                5.7|               741|
|   Seoul|from other city|1000007|       36| null|     null|      null|                   null|              null|            null|         null|                    null|               null|              null|
|   Seoul|  Dongdaemun-gu|1000008|       17|10110|37.574552|127.039721|                     21|                31|               4|         1.06|                   17.26|                6.7|               832|
|   Seoul|from other city|1000009|       25| null|     null|      null|                   null|              null|            null|         null|                    null|               null|              null|
|   Seoul|      Gwanak-gu|1000010|       30|10050| 37.47829|126.951502|                     22|                33|               1|         0.89|                   15.12|                4.9|               909|
|   Seoul|   Eunpyeong-gu|1000011|       14|10220|37.603481|126.929173|                     31|                44|               1|         1.09|                    17.0|                6.5|               874|
|   Seoul|   Seongdong-gu|1000012|       13|10160|37.563277|127.036647|                     21|                30|               2|         0.97|                   14.76|                5.3|               593|
|   Seoul|      Jongno-gu|1000013|       10|10230|37.572999|126.979189|                     13|                17|               3|         1.71|                   18.27|                6.8|               668|
|   Seoul|     Gangnam-gu|1000014|        7|10010|37.518421|127.047222|                     33|                38|               0|         4.18|                   13.17|                4.3|              3088|
|   Seoul|        Jung-gu|1000015|        7|10240|37.563988| 126.99753|                     12|                14|               2|         0.94|                   18.42|                7.4|               728|
|   Seoul|   Seodaemun-gu|1000016|        5|10140|37.579428|126.936771|                     19|                25|               6|         1.12|                   16.77|                6.2|               587|
|   Seoul|      Jongno-gu|1000017|        7|10230|37.572999|126.979189|                     13|                17|               3|         1.71|                   18.27|                6.8|               668|
|   Seoul|     Gangnam-gu|1000018|        6|10010|37.518421|127.047222|                     33|                38|               0|         4.18|                   13.17|                4.3|              3088|
|   Seoul|from other city|1000019|        1| null|     null|      null|                   null|              null|            null|         null|                    null|               null|              null|
|   Seoul|   Geumcheon-gu|1000020|        6|10080|37.456852|126.895229|                     18|                19|               0|         0.96|                   16.15|                6.7|               475|
+--------+---------------+-------+---------+-----+---------+----------+-----------------------+------------------+----------------+-------------+------------------------+-------------------+------------------+
only showing top 20 rows

In [46]:
case.show()

+-------+--------+---------------+---------+
|case_id|province|           city|confirmed|
+-------+--------+---------------+---------+
|1000001|   Seoul|     Yongsan-gu|      139|
|1000002|   Seoul|      Gwanak-gu|      119|
|1000003|   Seoul|        Guro-gu|       95|
|1000004|   Seoul|   Yangcheon-gu|       43|
|1000005|   Seoul|      Dobong-gu|       43|
|1000006|   Seoul|        Guro-gu|       41|
|1000007|   Seoul|from other city|       36|
|1000008|   Seoul|  Dongdaemun-gu|       17|
|1000009|   Seoul|from other city|       25|
|1000010|   Seoul|      Gwanak-gu|       30|
|1000011|   Seoul|   Eunpyeong-gu|       14|
|1000012|   Seoul|   Seongdong-gu|       13|
|1000013|   Seoul|      Jongno-gu|       10|
|1000014|   Seoul|     Gangnam-gu|        7|
|1000015|   Seoul|        Jung-gu|        7|
|1000016|   Seoul|   Seodaemun-gu|        5|
|1000017|   Seoul|      Jongno-gu|        7|
|1000018|   Seoul|     Gangnam-gu|        6|
|1000019|   Seoul|from other city|        1|
|1000020|   Seoul|   Geumcheon-gu|        6|
+-------+--------+---------------+---------+
only showing top 20 rows

<h3>Week 5 </h3>

In [47]:
def highlow(confirmed):
    if(confirmed<=50):
        return 'Low'
    return 'High'
user_func=F.udf(highlow,StringType())
new_case=case.withColumn('HighLow',user_func(case.confirmed))
new_case.show()

+-------+--------+---------------+---------+-------+
|case_id|province|           city|confirmed|HighLow|
+-------+--------+---------------+---------+-------+
|1000001|   Seoul|     Yongsan-gu|      139|   High|
|1000002|   Seoul|      Gwanak-gu|      119|   High|
|1000003|   Seoul|        Guro-gu|       95|   High|
|1000004|   Seoul|   Yangcheon-gu|       43|    Low|
|1000005|   Seoul|      Dobong-gu|       43|    Low|
|1000006|   Seoul|        Guro-gu|       41|    Low|
|1000007|   Seoul|from other city|       36|    Low|
|1000008|   Seoul|  Dongdaemun-gu|       17|    Low|
|1000009|   Seoul|from other city|       25|    Low|
|1000010|   Seoul|      Gwanak-gu|       30|    Low|
|1000011|   Seoul|   Eunpyeong-gu|       14|    Low|
|1000012|   Seoul|   Seongdong-gu|       13|    Low|
|1000013|   Seoul|      Jongno-gu|       10|    Low|
|1000014|   Seoul|     Gangnam-gu|        7|    Low|
|1000015|   Seoul|        Jung-gu|        7|    Low|
|1000016|   Seoul|   Seodaemun-gu|        5|    Low|
|1000017|   Seoul|      Jongno-gu|        7|    Low|
|1000018|   Seoul|     Gangnam-gu|        6|    Low|
|1000019|   Seoul|from other city|        1|    Low|
|1000020|   Seoul|   Geumcheon-gu|        6|    Low|
+-------+--------+---------------+---------+-------+
only showing top 20 rows

In [49]:
timeProvince=spark.read.load('TimeProvince.csv',format='csv',inferSchema=True,header=True)

In [53]:
from pyspark.sql.window import Window
window_frame=Window.partitionBy(['province']).orderBy('date')
new_col=timeProvince.withColumn('Lag_7',F.lag(F.col('confirmed'),7).over(window_frame))

In [54]:
new_col.show()

+----------+----+--------+---------+--------+--------+-----+
|      date|time|province|confirmed|released|deceased|Lag_7|
+----------+----+--------+---------+--------+--------+-----+
|2020-01-20|  16|   Busan|        0|       0|       0| null|
|2020-01-21|  16|   Busan|        0|       0|       0| null|
|2020-01-22|  16|   Busan|        0|       0|       0| null|
|2020-01-23|  16|   Busan|        0|       0|       0| null|
|2020-01-24|  16|   Busan|        0|       0|       0| null|
|2020-01-25|  16|   Busan|        0|       0|       0| null|
|2020-01-26|  16|   Busan|        0|       0|       0| null|
|2020-01-27|  16|   Busan|        0|       0|       0|    0|
|2020-01-28|  16|   Busan|        0|       0|       0|    0|
|2020-01-29|  16|   Busan|        0|       0|       0|    0|
|2020-01-30|  16|   Busan|        0|       0|       0|    0|
|2020-01-31|  16|   Busan|        0|       0|       0|    0|
|2020-02-01|  16|   Busan|        0|       0|       0|    0|
|2020-02-02|  16|   Busan|        0|       0|       0|    0|
|2020-02-03|  16|   Busan|        0|       0|       0|    0|
|2020-02-04|  16|   Busan|        0|       0|       0|    0|
|2020-02-05|  16|   Busan|        0|       0|       0|    0|
|2020-02-06|  16|   Busan|        0|       0|       0|    0|
|2020-02-07|  16|   Busan|        0|       0|       0|    0|
|2020-02-08|  16|   Busan|        0|       0|       0|    0|
+----------+----+--------+---------+--------+--------+-----+
only showing top 20 rows

In [56]:
new_col.filter(F.col('date')>'2020-03-11').show()

+----------+----+--------+---------+--------+--------+-----+
|      date|time|province|confirmed|released|deceased|Lag_7|
+----------+----+--------+---------+--------+--------+-----+
|2020-03-12|   0|   Busan|       99|      29|       0|   92|
|2020-03-13|   0|   Busan|      100|      36|       0|   95|
|2020-03-14|   0|   Busan|      103|      40|       0|   96|
|2020-03-15|   0|   Busan|      106|      52|       1|   96|
|2020-03-16|   0|   Busan|      107|      53|       1|   96|
|2020-03-17|   0|   Busan|      107|      54|       1|   96|
|2020-03-18|   0|   Busan|      107|      58|       1|   98|
|2020-03-19|   0|   Busan|      107|      58|       1|   99|
|2020-03-20|   0|   Busan|      108|      60|       1|  100|
|2020-03-21|   0|   Busan|      108|      67|       1|  103|
|2020-03-22|   0|   Busan|      108|      69|       1|  106|
|2020-03-23|   0|   Busan|      109|      71|       1|  107|
|2020-03-24|   0|   Busan|      111|      71|       1|  107|
|2020-03-25|   0|   Busan|      112|      73|       1|  107|
|2020-03-26|   0|   Busan|      112|      75|       2|  107|
|2020-03-27|   0|   Busan|      113|      81|       2|  108|
|2020-03-28|   0|   Busan|      114|      81|       2|  108|
|2020-03-29|   0|   Busan|      117|      85|       3|  108|
|2020-03-30|   0|   Busan|      118|      87|       3|  109|
|2020-03-31|   0|   Busan|      119|      87|       3|  111|
+----------+----+--------+---------+--------+--------+-----+
only showing top 20 rows

<h3>Lab 3  </h3>

In [76]:
text=spark.sparkContext.textFile('lab3.txt')

In [77]:
text.collect()

["Big Data refers to a massive set of data that no conventional data management tool can handle. Big Data is therefore a concept that allows access to gigantic databases in real time. Big Data's main objectives are to improve a company's or system's responsiveness to a large amount of data collected, increase productivity and refine knowledge of customer behavior, so that it can offer personalized offers or advertisements and create new trends.",
 'The Internet of Things (IoT) is a concept that connects physical or virtual objects to the internet. The technology very often used is the sensor, allowing to link a physical object such as a watch, a drone or even a speaker, to the internet. If for a long time the few objects connected to the Internet were the telephone and the computer, this is no longer the case today and every year new types of objects incorporating IOT technology are born. IOT is one of the greatest technological revolutions of our era and its potential for exploitation is immense. IOT could have a huge impact on the cars of the future or on the new versions of smart-cities, an urban space connected to the Internet, thus significantly improving the lives of users, while reducing the negative impact of these on the planet. ']

In [78]:
text.getNumPartitions()

2

In [79]:
text.take(2)

["Big Data refers to a massive set of data that no conventional data management tool can handle. Big Data is therefore a concept that allows access to gigantic databases in real time. Big Data's main objectives are to improve a company's or system's responsiveness to a large amount of data collected, increase productivity and refine knowledge of customer behavior, so that it can offer personalized offers or advertisements and create new trends.",
 'The Internet of Things (IoT) is a concept that connects physical or virtual objects to the internet. The technology very often used is the sensor, allowing to link a physical object such as a watch, a drone or even a speaker, to the internet. If for a long time the few objects connected to the Internet were the telephone and the computer, this is no longer the case today and every year new types of objects incorporating IOT technology are born. IOT is one of the greatest technological revolutions of our era and its potential for exploitation is immense. IOT could have a huge impact on the cars of the future or on the new versions of smart-cities, an urban space connected to the Internet, thus significantly improving the lives of users, while reducing the negative impact of these on the planet. ']

In [88]:
def Func(line):
    line=line.lower()
    
    line=line.split()
    return line
    

splitRdd=text.map(Func)

In [89]:
splitRdd.collect()

[['big',
  'data',
  'refers',
  'to',
  'a',
  'massive',
  'set',
  'of',
  'data',
  'that',
  'no',
  'conventional',
  'data',
  'management',
  'tool',
  'can',
  'handle.',
  'big',
  'data',
  'is',
  'therefore',
  'a',
  'concept',
  'that',
  'allows',
  'access',
  'to',
  'gigantic',
  'databases',
  'in',
  'real',
  'time.',
  'big',
  "data's",
  'main',
  'objectives',
  'are',
  'to',
  'improve',
  'a',
  "company's",
  'or',
  "system's",
  'responsiveness',
  'to',
  'a',
  'large',
  'amount',
  'of',
  'data',
  'collected,',
  'increase',
  'productivity',
  'and',
  'refine',
  'knowledge',
  'of',
  'customer',
  'behavior,',
  'so',
  'that',
  'it',
  'can',
  'offer',
  'personalized',
  'offers',
  'or',
  'advertisements',
  'and',
  'create',
  'new',
  'trends.'],
 ['the',
  'internet',
  'of',
  'things',
  '(iot)',
  'is',
  'a',
  'concept',
  'that',
  'connects',
  'physical',
  'or',
  'virtual',
  'objects',
  'to',
  'the',
  'internet.',
  'the',
  'technology',
  'very',
  'often',
  'used',
  'is',
  'the',
  'sensor,',
  'allowing',
  'to',
  'link',
  'a',
  'physical',
  'object',
  'such',
  'as',
  'a',
  'watch,',
  'a',
  'drone',
  'or',
  'even',
  'a',
  'speaker,',
  'to',
  'the',
  'internet.',
  'if',
  'for',
  'a',
  'long',
  'time',
  'the',
  'few',
  'objects',
  'connected',
  'to',
  'the',
  'internet',
  'were',
  'the',
  'telephone',
  'and',
  'the',
  'computer,',
  'this',
  'is',
  'no',
  'longer',
  'the',
  'case',
  'today',
  'and',
  'every',
  'year',
  'new',
  'types',
  'of',
  'objects',
  'incorporating',
  'iot',
  'technology',
  'are',
  'born.',
  'iot',
  'is',
  'one',
  'of',
  'the',
  'greatest',
  'technological',
  'revolutions',
  'of',
  'our',
  'era',
  'and',
  'its',
  'potential',
  'for',
  'exploitation',
  'is',
  'immense.',
  'iot',
  'could',
  'have',
  'a',
  'huge',
  'impact',
  'on',
  'the',
  'cars',
  'of',
  'the',
  'future',
  'or',
  'on',
  'the',
  'new',
  'versions',
  'of',
  'smart-cities,',
  'an',
  'urban',
  'space',
  'connected',
  'to',
  'the',
  'internet,',
  'thus',
  'significantly',
  'improving',
  'the',
  'lives',
  'of',
  'users,',
  'while',
  'reducing',
  'the',
  'negative',
  'impact',
  'of',
  'these',
  'on',
  'the',
  'planet.']]

In [91]:
splitRdd.take(2)

[['big',
  'data',
  'refers',
  'to',
  'a',
  'massive',
  'set',
  'of',
  'data',
  'that',
  'no',
  'conventional',
  'data',
  'management',
  'tool',
  'can',
  'handle.',
  'big',
  'data',
  'is',
  'therefore',
  'a',
  'concept',
  'that',
  'allows',
  'access',
  'to',
  'gigantic',
  'databases',
  'in',
  'real',
  'time.',
  'big',
  "data's",
  'main',
  'objectives',
  'are',
  'to',
  'improve',
  'a',
  "company's",
  'or',
  "system's",
  'responsiveness',
  'to',
  'a',
  'large',
  'amount',
  'of',
  'data',
  'collected,',
  'increase',
  'productivity',
  'and',
  'refine',
  'knowledge',
  'of',
  'customer',
  'behavior,',
  'so',
  'that',
  'it',
  'can',
  'offer',
  'personalized',
  'offers',
  'or',
  'advertisements',
  'and',
  'create',
  'new',
  'trends.'],
 ['the',
  'internet',
  'of',
  'things',
  '(iot)',
  'is',
  'a',
  'concept',
  'that',
  'connects',
  'physical',
  'or',
  'virtual',
  'objects',
  'to',
  'the',
  'internet.',
  'the',
  'technology',
  'very',
  'often',
  'used',
  'is',
  'the',
  'sensor,',
  'allowing',
  'to',
  'link',
  'a',
  'physical',
  'object',
  'such',
  'as',
  'a',
  'watch,',
  'a',
  'drone',
  'or',
  'even',
  'a',
  'speaker,',
  'to',
  'the',
  'internet.',
  'if',
  'for',
  'a',
  'long',
  'time',
  'the',
  'few',
  'objects',
  'connected',
  'to',
  'the',
  'internet',
  'were',
  'the',
  'telephone',
  'and',
  'the',
  'computer,',
  'this',
  'is',
  'no',
  'longer',
  'the',
  'case',
  'today',
  'and',
  'every',
  'year',
  'new',
  'types',
  'of',
  'objects',
  'incorporating',
  'iot',
  'technology',
  'are',
  'born.',
  'iot',
  'is',
  'one',
  'of',
  'the',
  'greatest',
  'technological',
  'revolutions',
  'of',
  'our',
  'era',
  'and',
  'its',
  'potential',
  'for',
  'exploitation',
  'is',
  'immense.',
  'iot',
  'could',
  'have',
  'a',
  'huge',
  'impact',
  'on',
  'the',
  'cars',
  'of',
  'the',
  'future',
  'or',
  'on',
  'the',
  'new',
  'versions',
  'of',
  'smart-cities,',
  'an',
  'urban',
  'space',
  'connected',
  'to',
  'the',
  'internet,',
  'thus',
  'significantly',
  'improving',
  'the',
  'lives',
  'of',
  'users,',
  'while',
  'reducing',
  'the',
  'negative',
  'impact',
  'of',
  'these',
  'on',
  'the',
  'planet.']]

In [92]:
flatRDD=text.flatMap(Func)
flatRDD.collect()

['big',
 'data',
 'refers',
 'to',
 'a',
 'massive',
 'set',
 'of',
 'data',
 'that',
 'no',
 'conventional',
 'data',
 'management',
 'tool',
 'can',
 'handle.',
 'big',
 'data',
 'is',
 'therefore',
 'a',
 'concept',
 'that',
 'allows',
 'access',
 'to',
 'gigantic',
 'databases',
 'in',
 'real',
 'time.',
 'big',
 "data's",
 'main',
 'objectives',
 'are',
 'to',
 'improve',
 'a',
 "company's",
 'or',
 "system's",
 'responsiveness',
 'to',
 'a',
 'large',
 'amount',
 'of',
 'data',
 'collected,',
 'increase',
 'productivity',
 'and',
 'refine',
 'knowledge',
 'of',
 'customer',
 'behavior,',
 'so',
 'that',
 'it',
 'can',
 'offer',
 'personalized',
 'offers',
 'or',
 'advertisements',
 'and',
 'create',
 'new',
 'trends.',
 'the',
 'internet',
 'of',
 'things',
 '(iot)',
 'is',
 'a',
 'concept',
 'that',
 'connects',
 'physical',
 'or',
 'virtual',
 'objects',
 'to',
 'the',
 'internet.',
 'the',
 'technology',
 'very',
 'often',
 'used',
 'is',
 'the',
 'sensor,',
 'allowing',
 'to',
 'link',
 'a',
 'physical',
 'object',
 'such',
 'as',
 'a',
 'watch,',
 'a',
 'drone',
 'or',
 'even',
 'a',
 'speaker,',
 'to',
 'the',
 'internet.',
 'if',
 'for',
 'a',
 'long',
 'time',
 'the',
 'few',
 'objects',
 'connected',
 'to',
 'the',
 'internet',
 'were',
 'the',
 'telephone',
 'and',
 'the',
 'computer,',
 'this',
 'is',
 'no',
 'longer',
 'the',
 'case',
 'today',
 'and',
 'every',
 'year',
 'new',
 'types',
 'of',
 'objects',
 'incorporating',
 'iot',
 'technology',
 'are',
 'born.',
 'iot',
 'is',
 'one',
 'of',
 'the',
 'greatest',
 'technological',
 'revolutions',
 'of',
 'our',
 'era',
 'and',
 'its',
 'potential',
 'for',
 'exploitation',
 'is',
 'immense.',
 'iot',
 'could',
 'have',
 'a',
 'huge',
 'impact',
 'on',
 'the',
 'cars',
 'of',
 'the',
 'future',
 'or',
 'on',
 'the',
 'new',
 'versions',
 'of',
 'smart-cities,',
 'an',
 'urban',
 'space',
 'connected',
 'to',
 'the',
 'internet,',
 'thus',
 'significantly',
 'improving',
 'the',
 'lives',
 'of',
 'users,',
 'while',
 'reducing',
 'the',
 'negative',
 'impact',
 'of',
 'these',
 'on',
 'the',
 'planet.']

In [94]:
flatRDD.take(5)

['big', 'data', 'refers', 'to', 'a']

In [95]:
stopWord=['a','an','the','of','so','to']


flatRDD.filter(lambda x: x not in stopWord).collect()

['big',
 'data',
 'refers',
 'massive',
 'set',
 'data',
 'that',
 'no',
 'conventional',
 'data',
 'management',
 'tool',
 'can',
 'handle.',
 'big',
 'data',
 'is',
 'therefore',
 'concept',
 'that',
 'allows',
 'access',
 'gigantic',
 'databases',
 'in',
 'real',
 'time.',
 'big',
 "data's",
 'main',
 'objectives',
 'are',
 'improve',
 "company's",
 'or',
 "system's",
 'responsiveness',
 'large',
 'amount',
 'data',
 'collected,',
 'increase',
 'productivity',
 'and',
 'refine',
 'knowledge',
 'customer',
 'behavior,',
 'that',
 'it',
 'can',
 'offer',
 'personalized',
 'offers',
 'or',
 'advertisements',
 'and',
 'create',
 'new',
 'trends.',
 'internet',
 'things',
 '(iot)',
 'is',
 'concept',
 'that',
 'connects',
 'physical',
 'or',
 'virtual',
 'objects',
 'internet.',
 'technology',
 'very',
 'often',
 'used',
 'is',
 'sensor,',
 'allowing',
 'link',
 'physical',
 'object',
 'such',
 'as',
 'watch,',
 'drone',
 'or',
 'even',
 'speaker,',
 'internet.',
 'if',
 'for',
 'long',
 'time',
 'few',
 'objects',
 'connected',
 'internet',
 'were',
 'telephone',
 'and',
 'computer,',
 'this',
 'is',
 'no',
 'longer',
 'case',
 'today',
 'and',
 'every',
 'year',
 'new',
 'types',
 'objects',
 'incorporating',
 'iot',
 'technology',
 'are',
 'born.',
 'iot',
 'is',
 'one',
 'greatest',
 'technological',
 'revolutions',
 'our',
 'era',
 'and',
 'its',
 'potential',
 'for',
 'exploitation',
 'is',
 'immense.',
 'iot',
 'could',
 'have',
 'huge',
 'impact',
 'on',
 'cars',
 'future',
 'or',
 'on',
 'new',
 'versions',
 'smart-cities,',
 'urban',
 'space',
 'connected',
 'internet,',
 'thus',
 'significantly',
 'improving',
 'lives',
 'users,',
 'while',
 'reducing',
 'negative',
 'impact',
 'these',
 'on',
 'planet.']

In [111]:
RDD2=flatRDD.filter(lambda x: x.startswith('d'))

In [112]:
RDD2.collect()

['data', 'data', 'data', 'data', 'databases', "data's", 'data', 'drone']

In [113]:
RDD2.distinct().collect()

['data', 'databases', "data's", 'drone']

In [114]:
a=spark.sparkContext.parallelize([1,2,3,4])
b=spark.sparkContext.parallelize([3,4,5,6])

In [117]:
a.union(b).collect()

[1, 2, 3, 4, 3, 4, 5, 6]

In [118]:
a.intersection(b).collect()

[3, 4]

In [119]:
a.subtract(b).collect()

[1, 2]

In [123]:
a.cartesian(b).collect()

[(1, 3),
 (1, 4),
 (1, 5),
 (1, 6),
 (2, 3),
 (2, 4),
 (2, 5),
 (2, 6),
 (3, 3),
 (3, 4),
 (3, 5),
 (3, 6),
 (4, 3),
 (4, 4),
 (4, 5),
 (4, 6)]

In [124]:
a=spark.sparkContext.parallelize([('a',1),('b',2),('c',3)])
b=spark.sparkContext.parallelize([('a',5),('d',8)])

In [125]:
a.join(b).collect()

[('a', (1, 5))]

In [126]:
n=spark.sparkContext.parallelize(range(1,1000))

In [127]:
n.reduce(lambda x,y:x+y)

499500

In [130]:
n=spark.sparkContext.parallelize(range(0,20),4)

In [131]:
n.getNumPartitions()

4

In [133]:
n.glom().collect()

[[0, 1, 2, 3, 4], [5, 6, 7, 8, 9], [10, 11, 12, 13, 14], [15, 16, 17, 18, 19]]

In [1]:
my=lambda x,y: x+y

my(1,2)

3

In [5]:
name ="Abdur Rahman Apu"

arr=lambda data: name.split(' ')

In [7]:
arr(name)

['Abdur', 'Rahman', 'Apu']

In [8]:
name.lower()

'abdur rahman apu'

In [9]:
name.find('a')

7

In [10]:
name

'Abdur Rahman Apu'

In [11]:
name.rfind('a')

10

In [12]:
name='    hello     '
name.lstrip()

'hello     '

In [13]:
name.rstrip()

'    hello'

In [14]:
name.strip()

'hello'

In [15]:
import findspark
findspark.init()

In [16]:
from pyspark.sql import SparkSession
spark=SparkSession.builder.appName('pi').getOrCreate()

In [17]:
spark

In [18]:
rdd=spark.sparkContext.parallelize([1,2,3,4,5,6])

In [19]:
rdd.collect()

[1, 2, 3, 4, 5, 6]

In [20]:
rdd.getNumPartitions()

4

In [21]:
rdd.glom().collect()

[[1], [2, 3], [4], [5, 6]]

In [23]:
rdd.filter(lambda x:x<3).collect()

[1, 2]

In [24]:
text=spark.sparkContext.textFile('lab3.txt')

In [25]:
text.collect()

["Big Data refers to a massive set of data that no conventional data management tool can handle. Big Data is therefore a concept that allows access to gigantic databases in real time. Big Data's main objectives are to improve a company's or system's responsiveness to a large amount of data collected, increase productivity and refine knowledge of customer behavior, so that it can offer personalized offers or advertisements and create new trends.",
 'The Internet of Things (IoT) is a concept that connects physical or virtual objects to the internet. The technology very often used is the sensor, allowing to link a physical object such as a watch, a drone or even a speaker, to the internet. If for a long time the few objects connected to the Internet were the telephone and the computer, this is no longer the case today and every year new types of objects incorporating IOT technology are born. IOT is one of the greatest technological revolutions of our era and its potential for exploitation is immense. IOT could have a huge impact on the cars of the future or on the new versions of smart-cities, an urban space connected to the Internet, thus significantly improving the lives of users, while reducing the negative impact of these on the planet. ']

In [26]:
def func(line):
    line=line.lower()
    line=line.split()
    return line
text.map(func).collect()

[['big',
  'data',
  'refers',
  'to',
  'a',
  'massive',
  'set',
  'of',
  'data',
  'that',
  'no',
  'conventional',
  'data',
  'management',
  'tool',
  'can',
  'handle.',
  'big',
  'data',
  'is',
  'therefore',
  'a',
  'concept',
  'that',
  'allows',
  'access',
  'to',
  'gigantic',
  'databases',
  'in',
  'real',
  'time.',
  'big',
  "data's",
  'main',
  'objectives',
  'are',
  'to',
  'improve',
  'a',
  "company's",
  'or',
  "system's",
  'responsiveness',
  'to',
  'a',
  'large',
  'amount',
  'of',
  'data',
  'collected,',
  'increase',
  'productivity',
  'and',
  'refine',
  'knowledge',
  'of',
  'customer',
  'behavior,',
  'so',
  'that',
  'it',
  'can',
  'offer',
  'personalized',
  'offers',
  'or',
  'advertisements',
  'and',
  'create',
  'new',
  'trends.'],
 ['the',
  'internet',
  'of',
  'things',
  '(iot)',
  'is',
  'a',
  'concept',
  'that',
  'connects',
  'physical',
  'or',
  'virtual',
  'objects',
  'to',
  'the',
  'internet.',
  'the',
  'technology',
  'very',
  'often',
  'used',
  'is',
  'the',
  'sensor,',
  'allowing',
  'to',
  'link',
  'a',
  'physical',
  'object',
  'such',
  'as',
  'a',
  'watch,',
  'a',
  'drone',
  'or',
  'even',
  'a',
  'speaker,',
  'to',
  'the',
  'internet.',
  'if',
  'for',
  'a',
  'long',
  'time',
  'the',
  'few',
  'objects',
  'connected',
  'to',
  'the',
  'internet',
  'were',
  'the',
  'telephone',
  'and',
  'the',
  'computer,',
  'this',
  'is',
  'no',
  'longer',
  'the',
  'case',
  'today',
  'and',
  'every',
  'year',
  'new',
  'types',
  'of',
  'objects',
  'incorporating',
  'iot',
  'technology',
  'are',
  'born.',
  'iot',
  'is',
  'one',
  'of',
  'the',
  'greatest',
  'technological',
  'revolutions',
  'of',
  'our',
  'era',
  'and',
  'its',
  'potential',
  'for',
  'exploitation',
  'is',
  'immense.',
  'iot',
  'could',
  'have',
  'a',
  'huge',
  'impact',
  'on',
  'the',
  'cars',
  'of',
  'the',
  'future',
  'or',
  'on',
  'the',
  'new',
  'versions',
  'of',
  'smart-cities,',
  'an',
  'urban',
  'space',
  'connected',
  'to',
  'the',
  'internet,',
  'thus',
  'significantly',
  'improving',
  'the',
  'lives',
  'of',
  'users,',
  'while',
  'reducing',
  'the',
  'negative',
  'impact',
  'of',
  'these',
  'on',
  'the',
  'planet.']]

In [28]:
rdd2=text.flatMap(func)

In [29]:
rdd2.collect()

['big',
 'data',
 'refers',
 'to',
 'a',
 'massive',
 'set',
 'of',
 'data',
 'that',
 'no',
 'conventional',
 'data',
 'management',
 'tool',
 'can',
 'handle.',
 'big',
 'data',
 'is',
 'therefore',
 'a',
 'concept',
 'that',
 'allows',
 'access',
 'to',
 'gigantic',
 'databases',
 'in',
 'real',
 'time.',
 'big',
 "data's",
 'main',
 'objectives',
 'are',
 'to',
 'improve',
 'a',
 "company's",
 'or',
 "system's",
 'responsiveness',
 'to',
 'a',
 'large',
 'amount',
 'of',
 'data',
 'collected,',
 'increase',
 'productivity',
 'and',
 'refine',
 'knowledge',
 'of',
 'customer',
 'behavior,',
 'so',
 'that',
 'it',
 'can',
 'offer',
 'personalized',
 'offers',
 'or',
 'advertisements',
 'and',
 'create',
 'new',
 'trends.',
 'the',
 'internet',
 'of',
 'things',
 '(iot)',
 'is',
 'a',
 'concept',
 'that',
 'connects',
 'physical',
 'or',
 'virtual',
 'objects',
 'to',
 'the',
 'internet.',
 'the',
 'technology',
 'very',
 'often',
 'used',
 'is',
 'the',
 'sensor,',
 'allowing',
 'to',
 'link',
 'a',
 'physical',
 'object',
 'such',
 'as',
 'a',
 'watch,',
 'a',
 'drone',
 'or',
 'even',
 'a',
 'speaker,',
 'to',
 'the',
 'internet.',
 'if',
 'for',
 'a',
 'long',
 'time',
 'the',
 'few',
 'objects',
 'connected',
 'to',
 'the',
 'internet',
 'were',
 'the',
 'telephone',
 'and',
 'the',
 'computer,',
 'this',
 'is',
 'no',
 'longer',
 'the',
 'case',
 'today',
 'and',
 'every',
 'year',
 'new',
 'types',
 'of',
 'objects',
 'incorporating',
 'iot',
 'technology',
 'are',
 'born.',
 'iot',
 'is',
 'one',
 'of',
 'the',
 'greatest',
 'technological',
 'revolutions',
 'of',
 'our',
 'era',
 'and',
 'its',
 'potential',
 'for',
 'exploitation',
 'is',
 'immense.',
 'iot',
 'could',
 'have',
 'a',
 'huge',
 'impact',
 'on',
 'the',
 'cars',
 'of',
 'the',
 'future',
 'or',
 'on',
 'the',
 'new',
 'versions',
 'of',
 'smart-cities,',
 'an',
 'urban',
 'space',
 'connected',
 'to',
 'the',
 'internet,',
 'thus',
 'significantly',
 'improving',
 'the',
 'lives',
 'of',
 'users,',
 'while',
 'reducing',
 'the',
 'negative',
 'impact',
 'of',
 'these',
 'on',
 'the',
 'planet.']

In [30]:
rdd2.take(5)

['big', 'data', 'refers', 'to', 'a']

In [31]:
stopword=['a','an','the','so','to']

rdd2.filter(lambda x: x not in stopword).collect()

['big',
 'data',
 'refers',
 'massive',
 'set',
 'of',
 'data',
 'that',
 'no',
 'conventional',
 'data',
 'management',
 'tool',
 'can',
 'handle.',
 'big',
 'data',
 'is',
 'therefore',
 'concept',
 'that',
 'allows',
 'access',
 'gigantic',
 'databases',
 'in',
 'real',
 'time.',
 'big',
 "data's",
 'main',
 'objectives',
 'are',
 'improve',
 "company's",
 'or',
 "system's",
 'responsiveness',
 'large',
 'amount',
 'of',
 'data',
 'collected,',
 'increase',
 'productivity',
 'and',
 'refine',
 'knowledge',
 'of',
 'customer',
 'behavior,',
 'that',
 'it',
 'can',
 'offer',
 'personalized',
 'offers',
 'or',
 'advertisements',
 'and',
 'create',
 'new',
 'trends.',
 'internet',
 'of',
 'things',
 '(iot)',
 'is',
 'concept',
 'that',
 'connects',
 'physical',
 'or',
 'virtual',
 'objects',
 'internet.',
 'technology',
 'very',
 'often',
 'used',
 'is',
 'sensor,',
 'allowing',
 'link',
 'physical',
 'object',
 'such',
 'as',
 'watch,',
 'drone',
 'or',
 'even',
 'speaker,',
 'internet.',
 'if',
 'for',
 'long',
 'time',
 'few',
 'objects',
 'connected',
 'internet',
 'were',
 'telephone',
 'and',
 'computer,',
 'this',
 'is',
 'no',
 'longer',
 'case',
 'today',
 'and',
 'every',
 'year',
 'new',
 'types',
 'of',
 'objects',
 'incorporating',
 'iot',
 'technology',
 'are',
 'born.',
 'iot',
 'is',
 'one',
 'of',
 'greatest',
 'technological',
 'revolutions',
 'of',
 'our',
 'era',
 'and',
 'its',
 'potential',
 'for',
 'exploitation',
 'is',
 'immense.',
 'iot',
 'could',
 'have',
 'huge',
 'impact',
 'on',
 'cars',
 'of',
 'future',
 'or',
 'on',
 'new',
 'versions',
 'of',
 'smart-cities,',
 'urban',
 'space',
 'connected',
 'internet,',
 'thus',
 'significantly',
 'improving',
 'lives',
 'of',
 'users,',
 'while',
 'reducing',
 'negative',
 'impact',
 'of',
 'these',
 'on',
 'planet.']

In [41]:
rdd2.filter(lambda x: x.startswith('d')).distinct().collect()

['data', 'databases', "data's", 'drone']

In [40]:
rdd3.collect()

['data', 'data', 'data', 'data', 'databases', "data's", 'data', 'drone']

In [45]:
a=spark.sparkContext.parallelize([('a',1),('b',2)])
b=spark.sparkContext.parallelize([('a',4)])
a.join(b).collect()

[('a', (1, 4))]

In [46]:
a=spark.sparkContext.parallelize([1,2,3,4])
b=spark.sparkContext.parallelize([2,3,4,5])

In [47]:
a.union(b).collect()

[1, 2, 3, 4, 2, 3, 4, 5]

In [48]:
a.intersection(b).collect()

[2, 3, 4]

In [49]:
a.subtract(b).collect()

[1]

In [50]:
a.cartesian(b).collect()

[(1, 2),
 (1, 3),
 (1, 4),
 (1, 5),
 (2, 2),
 (2, 3),
 (2, 4),
 (2, 5),
 (3, 2),
 (3, 3),
 (3, 4),
 (3, 5),
 (4, 2),
 (4, 3),
 (4, 4),
 (4, 5)]

In [52]:
n=spark.sparkContext.parallelize(range(0,1000))
n.reduce(lambda x,y:x+y)

499500

In [53]:
case=spark.read.load('case.csv',format='csv',inferSchema=True,header=True)

In [54]:
case.show()

+--------+--------+---------------+-----+--------------------+---------+---------+----------+
| case_id|province|           city|group|      infection_case|confirmed| latitude| longitude|
+--------+--------+---------------+-----+--------------------+---------+---------+----------+
| 1000001|   Seoul|     Yongsan-gu| true|       Itaewon Clubs|      139|37.538621|126.992652|
| 1000002|   Seoul|      Gwanak-gu| true|             Richway|      119| 37.48208|126.901384|
| 1000003|   Seoul|        Guro-gu| true| Guro-gu Call Center|       95|37.508163|126.884387|
| 1000004|   Seoul|   Yangcheon-gu| true|Yangcheon Table T...|       43|37.546061|126.874209|
| 1000005|   Seoul|      Dobong-gu| true|     Day Care Center|       43|37.679422|127.044374|
| 1000006|   Seoul|        Guro-gu| true|Manmin Central Ch...|       41|37.481059|126.894343|
| 1000007|   Seoul|from other city| true|SMR Newly Planted...|       36|        -|         -|
| 1000008|   Seoul|  Dongdaemun-gu| true|       Dongan Church|       17|37.592888|127.056766|
| 1000009|   Seoul|from other city| true|Coupang Logistics...|       25|        -|         -|
| 1000010|   Seoul|      Gwanak-gu| true|     Wangsung Church|       30|37.481735|126.930121|
| 1000011|   Seoul|   Eunpyeong-gu| true|Eunpyeong St. Mar...|       14| 37.63369|  126.9165|
| 1000012|   Seoul|   Seongdong-gu| true|    Seongdong-gu APT|       13| 37.55713|  127.0403|
| 1000013|   Seoul|      Jongno-gu| true|Jongno Community ...|       10| 37.57681|   127.006|
| 1000014|   Seoul|     Gangnam-gu| true|Samsung Medical C...|        7| 37.48825| 127.08559|
| 1000015|   Seoul|        Jung-gu| true|Jung-gu Fashion C...|        7|37.562405|126.984377|
| 1000016|   Seoul|   Seodaemun-gu| true|  Yeonana News Class|        5|37.558147|126.943799|
| 1000017|   Seoul|      Jongno-gu| true|Korea Campus Crus...|        7|37.594782|126.968022|
| 1000018|   Seoul|     Gangnam-gu| true|Gangnam Yeoksam-d...|        6|        -|         -|
| 1000019|   Seoul|from other city| true|Daejeon door-to-d...|        1|        -|         -|
| 1000020|   Seoul|   Geumcheon-gu| true|Geumcheon-gu rice...|        6|        -|         -|
+--------+--------+---------------+-----+--------------------+---------+---------+----------+
only showing top 20 rows

In [55]:
case.printSchema()

root
 |--  case_id: integer (nullable = true)
 |-- province: string (nullable = true)
 |-- city: string (nullable = true)
 |-- group: boolean (nullable = true)
 |-- infection_case: string (nullable = true)
 |-- confirmed: integer (nullable = true)
 |-- latitude: string (nullable = true)
 |-- longitude: string (nullable = true)

In [56]:
case=case.withColumnRenamed("infection_case","infection_source")

In [57]:
case.show()

+--------+--------+---------------+-----+--------------------+---------+---------+----------+
| case_id|province|           city|group|    infection_source|confirmed| latitude| longitude|
+--------+--------+---------------+-----+--------------------+---------+---------+----------+
| 1000001|   Seoul|     Yongsan-gu| true|       Itaewon Clubs|      139|37.538621|126.992652|
| 1000002|   Seoul|      Gwanak-gu| true|             Richway|      119| 37.48208|126.901384|
| 1000003|   Seoul|        Guro-gu| true| Guro-gu Call Center|       95|37.508163|126.884387|
| 1000004|   Seoul|   Yangcheon-gu| true|Yangcheon Table T...|       43|37.546061|126.874209|
| 1000005|   Seoul|      Dobong-gu| true|     Day Care Center|       43|37.679422|127.044374|
| 1000006|   Seoul|        Guro-gu| true|Manmin Central Ch...|       41|37.481059|126.894343|
| 1000007|   Seoul|from other city| true|SMR Newly Planted...|       36|        -|         -|
| 1000008|   Seoul|  Dongdaemun-gu| true|       Dongan Church|       17|37.592888|127.056766|
| 1000009|   Seoul|from other city| true|Coupang Logistics...|       25|        -|         -|
| 1000010|   Seoul|      Gwanak-gu| true|     Wangsung Church|       30|37.481735|126.930121|
| 1000011|   Seoul|   Eunpyeong-gu| true|Eunpyeong St. Mar...|       14| 37.63369|  126.9165|
| 1000012|   Seoul|   Seongdong-gu| true|    Seongdong-gu APT|       13| 37.55713|  127.0403|
| 1000013|   Seoul|      Jongno-gu| true|Jongno Community ...|       10| 37.57681|   127.006|
| 1000014|   Seoul|     Gangnam-gu| true|Samsung Medical C...|        7| 37.48825| 127.08559|
| 1000015|   Seoul|        Jung-gu| true|Jung-gu Fashion C...|        7|37.562405|126.984377|
| 1000016|   Seoul|   Seodaemun-gu| true|  Yeonana News Class|        5|37.558147|126.943799|
| 1000017|   Seoul|      Jongno-gu| true|Korea Campus Crus...|        7|37.594782|126.968022|
| 1000018|   Seoul|     Gangnam-gu| true|Gangnam Yeoksam-d...|        6|        -|         -|
| 1000019|   Seoul|from other city| true|Daejeon door-to-d...|        1|        -|         -|
| 1000020|   Seoul|   Geumcheon-gu| true|Geumcheon-gu rice...|        6|        -|         -|
+--------+--------+---------------+-----+--------------------+---------+---------+----------+
only showing top 20 rows

In [58]:
case=case.select("province",'city','infection_source','confirmed')

In [59]:
case.show()

+--------+---------------+--------------------+---------+
|province|           city|    infection_source|confirmed|
+--------+---------------+--------------------+---------+
|   Seoul|     Yongsan-gu|       Itaewon Clubs|      139|
|   Seoul|      Gwanak-gu|             Richway|      119|
|   Seoul|        Guro-gu| Guro-gu Call Center|       95|
|   Seoul|   Yangcheon-gu|Yangcheon Table T...|       43|
|   Seoul|      Dobong-gu|     Day Care Center|       43|
|   Seoul|        Guro-gu|Manmin Central Ch...|       41|
|   Seoul|from other city|SMR Newly Planted...|       36|
|   Seoul|  Dongdaemun-gu|       Dongan Church|       17|
|   Seoul|from other city|Coupang Logistics...|       25|
|   Seoul|      Gwanak-gu|     Wangsung Church|       30|
|   Seoul|   Eunpyeong-gu|Eunpyeong St. Mar...|       14|
|   Seoul|   Seongdong-gu|    Seongdong-gu APT|       13|
|   Seoul|      Jongno-gu|Jongno Community ...|       10|
|   Seoul|     Gangnam-gu|Samsung Medical C...|        7|
|   Seoul|        Jung-gu|Jung-gu Fashion C...|        7|
|   Seoul|   Seodaemun-gu|  Yeonana News Class|        5|
|   Seoul|      Jongno-gu|Korea Campus Crus...|        7|
|   Seoul|     Gangnam-gu|Gangnam Yeoksam-d...|        6|
|   Seoul|from other city|Daejeon door-to-d...|        1|
|   Seoul|   Geumcheon-gu|Geumcheon-gu rice...|        6|
+--------+---------------+--------------------+---------+
only showing top 20 rows

In [60]:
case=case.toDF(*['province','city','infection_case','confirmed'])

In [61]:
case.show()

+--------+---------------+--------------------+---------+
|province|           city|      infection_case|confirmed|
+--------+---------------+--------------------+---------+
|   Seoul|     Yongsan-gu|       Itaewon Clubs|      139|
|   Seoul|      Gwanak-gu|             Richway|      119|
|   Seoul|        Guro-gu| Guro-gu Call Center|       95|
|   Seoul|   Yangcheon-gu|Yangcheon Table T...|       43|
|   Seoul|      Dobong-gu|     Day Care Center|       43|
|   Seoul|        Guro-gu|Manmin Central Ch...|       41|
|   Seoul|from other city|SMR Newly Planted...|       36|
|   Seoul|  Dongdaemun-gu|       Dongan Church|       17|
|   Seoul|from other city|Coupang Logistics...|       25|
|   Seoul|      Gwanak-gu|     Wangsung Church|       30|
|   Seoul|   Eunpyeong-gu|Eunpyeong St. Mar...|       14|
|   Seoul|   Seongdong-gu|    Seongdong-gu APT|       13|
|   Seoul|      Jongno-gu|Jongno Community ...|       10|
|   Seoul|     Gangnam-gu|Samsung Medical C...|        7|
|   Seoul|        Jung-gu|Jung-gu Fashion C...|        7|
|   Seoul|   Seodaemun-gu|  Yeonana News Class|        5|
|   Seoul|      Jongno-gu|Korea Campus Crus...|        7|
|   Seoul|     Gangnam-gu|Gangnam Yeoksam-d...|        6|
|   Seoul|from other city|Daejeon door-to-d...|        1|
|   Seoul|   Geumcheon-gu|Geumcheon-gu rice...|        6|
+--------+---------------+--------------------+---------+
only showing top 20 rows

In [64]:
case.sort('confirmed').show()

+-----------------+---------------+--------------------+---------+
|         province|           city|      infection_case|confirmed|
+-----------------+---------------+--------------------+---------+
|          Jeju-do|              -|contact with patient|        0|
|       Gangwon-do|              -|contact with patient|        0|
|            Seoul|     Gangseo-gu|SJ Investment Cal...|        0|
|            Busan|from other city|Cheongdo Daenam H...|        1|
|     Jeollabuk-do|from other city|  Shincheonji Church|        1|
|            Seoul|from other city|Anyang Gunpo Past...|        1|
|            Seoul|     Gangnam-gu|Gangnam Dongin Ch...|        1|
|           Sejong|from other city|  Shincheonji Church|        1|
|     Jeollanam-do|from other city|  Shincheonji Church|        1|
|          Jeju-do|from other city|       Itaewon Clubs|        1|
|            Seoul|from other city|Daejeon door-to-d...|        1|
|            Seoul|              -|         Orange Life|        1|
|           Sejong|              -|                 etc|        1|
|          Gwangju|              -|                 etc|        1|
|            Daegu|from other city|       Itaewon Clubs|        2|
|            Daegu|from other city|Cheongdo Daenam H...|        2|
|          Incheon|from other city|  Shincheonji Church|        2|
|            Seoul|from other city|Uiwang Logistics ...|        2|
|          Daejeon|from other city|  Shincheonji Church|        2|
|Chungcheongbuk-do|from other city| Guro-gu Call Center|        2|
+-----------------+---------------+--------------------+---------+
only showing top 20 rows

In [65]:
from pyspark.sql import functions as F
from pyspark.sql.types import *

In [66]:
case=case.sort(F.desc('confirmed'))
case.show()

+-----------------+---------------+--------------------+---------+
|         province|           city|      infection_case|confirmed|
+-----------------+---------------+--------------------+---------+
|            Daegu|         Nam-gu|  Shincheonji Church|     4511|
|            Daegu|              -|contact with patient|      917|
|            Daegu|              -|                 etc|      747|
| Gyeongsangbuk-do|from other city|  Shincheonji Church|      566|
|      Gyeonggi-do|              -|     overseas inflow|      305|
|            Seoul|              -|     overseas inflow|      298|
|            Daegu|   Dalseong-gun|Second Mi-Ju Hosp...|      196|
| Gyeongsangbuk-do|              -|contact with patient|      190|
|            Seoul|              -|contact with patient|      162|
|            Seoul|     Yongsan-gu|       Itaewon Clubs|      139|
| Gyeongsangbuk-do|              -|                 etc|      133|
|            Daegu|         Seo-gu|Hansarang Convale...|      124|
|            Seoul|      Gwanak-gu|             Richway|      119|
| Gyeongsangbuk-do|   Cheongdo-gun|Cheongdo Daenam H...|      119|
|Chungcheongnam-do|     Cheonan-si|gym facility in C...|      103|
|            Daegu|   Dalseong-gun|Daesil Convalesce...|      101|
|            Seoul|              -|                 etc|      100|
|            Seoul|        Guro-gu| Guro-gu Call Center|       95|
|      Gyeonggi-do|              -|                 etc|       84|
|          Incheon|              -|     overseas inflow|       68|
+-----------------+---------------+--------------------+---------+
only showing top 20 rows

In [68]:
case=case.withColumn("confirmed",F.col('confirmed').cast(IntegerType()))
case.show()

+-----------------+---------------+--------------------+---------+
|         province|           city|      infection_case|confirmed|
+-----------------+---------------+--------------------+---------+
|            Daegu|         Nam-gu|  Shincheonji Church|     4511|
|            Daegu|              -|contact with patient|      917|
|            Daegu|              -|                 etc|      747|
| Gyeongsangbuk-do|from other city|  Shincheonji Church|      566|
|      Gyeonggi-do|              -|     overseas inflow|      305|
|            Seoul|              -|     overseas inflow|      298|
|            Daegu|   Dalseong-gun|Second Mi-Ju Hosp...|      196|
| Gyeongsangbuk-do|              -|contact with patient|      190|
|            Seoul|              -|contact with patient|      162|
|            Seoul|     Yongsan-gu|       Itaewon Clubs|      139|
| Gyeongsangbuk-do|              -|                 etc|      133|
|            Daegu|         Seo-gu|Hansarang Convale...|      124|
|            Seoul|      Gwanak-gu|             Richway|      119|
| Gyeongsangbuk-do|   Cheongdo-gun|Cheongdo Daenam H...|      119|
|Chungcheongnam-do|     Cheonan-si|gym facility in C...|      103|
|            Daegu|   Dalseong-gun|Daesil Convalesce...|      101|
|            Seoul|              -|                 etc|      100|
|            Seoul|        Guro-gu| Guro-gu Call Center|       95|
|      Gyeonggi-do|              -|                 etc|       84|
|          Incheon|              -|     overseas inflow|       68|
+-----------------+---------------+--------------------+---------+
only showing top 20 rows

In [73]:
case.filter((case.confirmed<200) & ((case.city=='Yongsan-gu') | (case.city=="Guro-gu"))).show()

+--------+----------+--------------------+---------+
|province|      city|      infection_case|confirmed|
+--------+----------+--------------------+---------+
|   Seoul|Yongsan-gu|       Itaewon Clubs|      139|
|   Seoul|   Guro-gu| Guro-gu Call Center|       95|
|   Seoul|   Guro-gu|Manmin Central Ch...|       41|
|   Seoul|   Guro-gu|     Daezayeon Korea|        3|
+--------+----------+--------------------+---------+

In [75]:
case.groupBy(['province','city']).agg(F.sum('confirmed').alias('Sum of confirmed'),F.max('confirmed').alias("Max confirmed")).show()

+----------------+---------------+----------------+-------------+
|        province|           city|Sum of confirmed|Max confirmed|
+----------------+---------------+----------------+-------------+
|Gyeongsangnam-do|       Jinju-si|               9|            9|
|           Seoul|        Guro-gu|             139|           95|
|           Seoul|     Gangnam-gu|              18|            7|
|         Daejeon|              -|             100|           55|
|    Jeollabuk-do|from other city|               6|            3|
|Gyeongsangnam-do|Changnyeong-gun|               7|            7|
|           Seoul|              -|             561|          298|
|         Jeju-do|from other city|               1|            1|
|Gyeongsangbuk-do|              -|             345|          190|
|Gyeongsangnam-do|   Geochang-gun|              18|           10|
|Gyeongsangbuk-do|        Gumi-si|              10|           10|
|         Incheon|from other city|             117|           53|
|           Busan|              -|              85|           36|
|           Daegu|         Seo-gu|             124|          124|
|           Busan|     Suyeong-gu|               5|            5|
|     Gyeonggi-do|   Uijeongbu-si|              50|           50|
|           Seoul|     Yongsan-gu|             139|          139|
|           Daegu|              -|            1705|          917|
|           Seoul|   Seodaemun-gu|               5|            5|
|     Gyeonggi-do|    Seongnam-si|              94|           67|
+----------------+---------------+----------------+-------------+
only showing top 20 rows

In [76]:
region=spark.read.load('region.csv',format="csv",inferSchema=True,header=True)
region.show()

+-----+--------+-------------+---------+----------+-----------------------+------------------+----------------+-------------+------------------------+-------------------+------------------+
| code|province|         city| latitude| longitude|elementary_school_count|kindergarten_count|university_count|academy_ratio|elderly_population_ratio|elderly_alone_ratio|nursing_home_count|
+-----+--------+-------------+---------+----------+-----------------------+------------------+----------------+-------------+------------------------+-------------------+------------------+
|10000|   Seoul|        Seoul|37.566953|126.977977|                    607|               830|              48|         1.44|                   15.38|                5.8|             22739|
|10010|   Seoul|   Gangnam-gu|37.518421|127.047222|                     33|                38|               0|         4.18|                   13.17|                4.3|              3088|
|10020|   Seoul|  Gangdong-gu|37.530492|127.123837|                     27|                32|               0|         1.54|                   14.55|                5.4|              1023|
|10030|   Seoul|   Gangbuk-gu|37.639938|127.025508|                     14|                21|               0|         0.67|                   19.49|                8.5|               628|
|10040|   Seoul|   Gangseo-gu|37.551166|126.849506|                     36|                56|               1|         1.17|                   14.39|                5.7|              1080|
|10050|   Seoul|    Gwanak-gu| 37.47829|126.951502|                     22|                33|               1|         0.89|                   15.12|                4.9|               909|
|10060|   Seoul|  Gwangjin-gu|37.538712|127.082366|                     22|                33|               3|         1.16|                   13.75|                4.8|               723|
|10070|   Seoul|      Guro-gu|37.495632| 126.88765|                     26|                34|               3|          1.0|                   16.21|                5.7|               741|
|10080|   Seoul| Geumcheon-gu|37.456852|126.895229|                     18|                19|               0|         0.96|                   16.15|                6.7|               475|
|10090|   Seoul|     Nowon-gu|37.654259|127.056294|                     42|                66|               6|         1.39|                    15.4|                7.4|               952|
|10100|   Seoul|    Dobong-gu|37.668952|127.047082|                     23|                26|               1|         0.95|                   17.89|                7.2|               485|
|10110|   Seoul|Dongdaemun-gu|37.574552|127.039721|                     21|                31|               4|         1.06|                   17.26|                6.7|               832|
|10120|   Seoul|   Dongjak-gu|37.510571|126.963604|                     21|                34|               3|         1.17|                   15.85|                5.2|               762|
|10130|   Seoul|      Mapo-gu|37.566283|126.901644|                     22|                24|               2|         1.83|                   14.05|                4.9|               929|
|10140|   Seoul| Seodaemun-gu|37.579428|126.936771|                     19|                25|               6|         1.12|                   16.77|                6.2|               587|
|10150|   Seoul|    Seocho-gu|37.483804|127.032693|                     24|                27|               1|          2.6|                   13.39|                3.8|              1465|
|10160|   Seoul| Seongdong-gu|37.563277|127.036647|                     21|                30|               2|         0.97|                   14.76|                5.3|               593|
|10170|   Seoul|  Seongbuk-gu|37.589562|  127.0167|                     29|                49|               6|         1.02|                   16.15|                6.0|               729|
|10180|   Seoul|    Songpa-gu| 37.51462|127.106141|                     40|                51|               1|         1.65|                    13.1|                4.1|              1527|
|10190|   Seoul| Yangcheon-gu|37.517189|126.866618|                     30|                43|               0|         2.26|                   13.55|                5.5|               816|
+-----+--------+-------------+---------+----------+-----------------------+------------------+----------------+-------------+------------------------+-------------------+------------------+
only showing top 20 rows

In [77]:
case.join(region,['province','city'],how='left').show()

+-----------------+---------------+--------------------+---------+-----+---------+----------+-----------------------+------------------+----------------+-------------+------------------------+-------------------+------------------+
|         province|           city|      infection_case|confirmed| code| latitude| longitude|elementary_school_count|kindergarten_count|university_count|academy_ratio|elderly_population_ratio|elderly_alone_ratio|nursing_home_count|
+-----------------+---------------+--------------------+---------+-----+---------+----------+-----------------------+------------------+----------------+-------------+------------------------+-------------------+------------------+
|            Daegu|         Nam-gu|  Shincheonji Church|     4511|12010|  35.8463|128.597723|                     11|                15|               2|         0.85|                   22.49|               10.4|               345|
|            Daegu|              -|contact with patient|      917| null|     null|      null|                   null|              null|            null|         null|                    null|               null|              null|
|            Daegu|              -|                 etc|      747| null|     null|      null|                   null|              null|            null|         null|                    null|               null|              null|
| Gyeongsangbuk-do|from other city|  Shincheonji Church|      566| null|     null|      null|                   null|              null|            null|         null|                    null|               null|              null|
|      Gyeonggi-do|              -|     overseas inflow|      305| null|     null|      null|                   null|              null|            null|         null|                    null|               null|              null|
|            Seoul|              -|     overseas inflow|      298| null|     null|      null|                   null|              null|            null|         null|                    null|               null|              null|
|            Daegu|   Dalseong-gun|Second Mi-Ju Hosp...|      196|12030| 35.77475|128.431314|                     32|                47|               1|         1.51|                   12.11|                5.4|               361|
| Gyeongsangbuk-do|              -|contact with patient|      190| null|     null|      null|                   null|              null|            null|         null|                    null|               null|              null|
|            Seoul|              -|contact with patient|      162| null|     null|      null|                   null|              null|            null|         null|                    null|               null|              null|
|            Seoul|     Yongsan-gu|       Itaewon Clubs|      139|10210|37.532768|126.990021|                     15|                13|               1|         0.68|                   16.87|                6.5|               435|
| Gyeongsangbuk-do|              -|                 etc|      133| null|     null|      null|                   null|              null|            null|         null|                    null|               null|              null|
|            Daegu|         Seo-gu|Hansarang Convale...|      124|12060|35.871993|128.559182|                     17|                23|               0|         0.83|                   21.29|               10.1|               374|
|            Seoul|      Gwanak-gu|             Richway|      119|10050| 37.47829|126.951502|                     22|                33|               1|         0.89|                   15.12|                4.9|               909|
| Gyeongsangbuk-do|   Cheongdo-gun|Cheongdo Daenam H...|      119|60200|35.647361|128.734382|                     11|                14|               0|         0.63|                   36.55|               21.0|                85|
|Chungcheongnam-do|     Cheonan-si|gym facility in C...|      103|41120| 36.81498|127.113868|                     75|               112|               6|         1.91|                   10.42|                4.5|              1069|
|            Daegu|   Dalseong-gun|Daesil Convalesce...|      101|12030| 35.77475|128.431314|                     32|                47|               1|         1.51|                   12.11|                5.4|               361|
|            Seoul|              -|                 etc|      100| null|     null|      null|                   null|              null|            null|         null|                    null|               null|              null|
|            Seoul|        Guro-gu| Guro-gu Call Center|       95|10070|37.495632| 126.88765|                     26|                34|               3|          1.0|                   16.21|                5.7|               741|
|      Gyeonggi-do|              -|                 etc|       84| null|     null|      null|                   null|              null|            null|         null|                    null|               null|              null|
|          Incheon|              -|     overseas inflow|       68| null|     null|      null|                   null|              null|            null|         null|                    null|               null|              null|
+-----------------+---------------+--------------------+---------+-----+---------+----------+-----------------------+------------------+----------------+-------------+------------------------+-------------------+------------------+
only showing top 20 rows

In [78]:
case.limit(10).toPandas()

           province             city         infection_case  confirmed
0             Daegu           Nam-gu     Shincheonji Church       4511
1             Daegu                -   contact with patient        917
2             Daegu                -                    etc        747
3  Gyeongsangbuk-do  from other city     Shincheonji Church        566
4       Gyeonggi-do                -        overseas inflow        305
5             Seoul                -        overseas inflow        298
6             Daegu     Dalseong-gun  Second Mi-Ju Hospital        196
7  Gyeongsangbuk-do                -   contact with patient        190
8             Seoul                -   contact with patient        162
9             Seoul       Yongsan-gu          Itaewon Clubs        139

In [79]:
text.collect()

["Big Data refers to a massive set of data that no conventional data management tool can handle. Big Data is therefore a concept that allows access to gigantic databases in real time. Big Data's main objectives are to improve a company's or system's responsiveness to a large amount of data collected, increase productivity and refine knowledge of customer behavior, so that it can offer personalized offers or advertisements and create new trends.",
 'The Internet of Things (IoT) is a concept that connects physical or virtual objects to the internet. The technology very often used is the sensor, allowing to link a physical object such as a watch, a drone or even a speaker, to the internet. If for a long time the few objects connected to the Internet were the telephone and the computer, this is no longer the case today and every year new types of objects incorporating IOT technology are born. IOT is one of the greatest technological revolutions of our era and its potential for exploitation is immense. IOT could have a huge impact on the cars of the future or on the new versions of smart-cities, an urban space connected to the Internet, thus significantly improving the lives of users, while reducing the negative impact of these on the planet. ']

In [83]:
text=text.flatMap(lambda x:x.split(' ')).map(lambda word: (word,1)).reduceByKey(lambda x,y:x+y)
text.collect()

[('refers', 1),
 ('massive', 1),
 ('set', 1),
 ('of', 11),
 ('no', 2),
 ('conventional', 1),
 ('management', 1),
 ('is', 6),
 ('in', 1),
 ("Data's", 1),
 ('objectives', 1),
 ('are', 2),
 ('improve', 1),
 ("company's", 1),
 ("system's", 1),
 ('large', 1),
 ('amount', 1),
 ('collected,', 1),
 ('increase', 1),
 ('knowledge', 1),
 ('customer', 1),
 ('personalized', 1),
 ('offers', 1),
 ('new', 3),
 ('The', 2),
 ('Things', 1),
 ('(IoT)', 1),
 ('connects', 1),
 ('internet.', 2),
 ('technology', 2),
 ('very', 1),
 ('used', 1),
 ('sensor,', 1),
 ('allowing', 1),
 ('as', 1),
 ('watch,', 1),
 ('even', 1),
 ('speaker,', 1),
 ('long', 1),
 ('telephone', 1),
 ('computer,', 1),
 ('this', 1),
 ('longer', 1),
 ('year', 1),
 ('incorporating', 1),
 ('IOT', 3),
 ('born.', 1),
 ('greatest', 1),
 ('potential', 1),
 ('exploitation', 1),
 ('have', 1),
 ('huge', 1),
 ('versions', 1),
 ('an', 1),
 ('space', 1),
 ('Internet,', 1),
 ('thus', 1),
 ('significantly', 1),
 ('reducing', 1),
 ('negative', 1),
 ('these', 1),
 ('planet.', 1),
 ('', 1),
 ('Big', 3),
 ('Data', 2),
 ('to', 9),
 ('a', 11),
 ('data', 3),
 ('that', 4),
 ('tool', 1),
 ('can', 2),
 ('handle.', 1),
 ('therefore', 1),
 ('concept', 2),
 ('allows', 1),
 ('access', 1),
 ('gigantic', 1),
 ('databases', 1),
 ('real', 1),
 ('time.', 1),
 ('main', 1),
 ('or', 5),
 ('responsiveness', 1),
 ('productivity', 1),
 ('and', 5),
 ('refine', 1),
 ('behavior,', 1),
 ('so', 1),
 ('it', 1),
 ('offer', 1),
 ('advertisements', 1),
 ('create', 1),
 ('trends.', 1),
 ('Internet', 2),
 ('physical', 2),
 ('virtual', 1),
 ('objects', 3),
 ('the', 16),
 ('often', 1),
 ('link', 1),
 ('object', 1),
 ('such', 1),
 ('drone', 1),
 ('If', 1),
 ('for', 2),
 ('time', 1),
 ('few', 1),
 ('connected', 2),
 ('were', 1),
 ('case', 1),
 ('today', 1),
 ('every', 1),
 ('types', 1),
 ('one', 1),
 ('technological', 1),
 ('revolutions', 1),
 ('our', 1),
 ('era', 1),
 ('its', 1),
 ('immense.', 1),
 ('could', 1),
 ('impact', 2),
 ('on', 3),
 ('cars', 1),
 ('future', 1),
 ('smart-cities,', 1),
 ('urban', 1),
 ('improving', 1),
 ('lives', 1),
 ('users,', 1),
 ('while', 1)]

In [84]:
text.saveAsTextFile('text')

Py4JJavaError: An error occurred while calling o783.saveAsTextFile.
: org.apache.spark.SparkException: Job aborted.
	at org.apache.spark.internal.io.SparkHadoopWriter$.write(SparkHadoopWriter.scala:106)
	at org.apache.spark.rdd.PairRDDFunctions.$anonfun$saveAsHadoopDataset$1(PairRDDFunctions.scala:1090)
	at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:23)
	at org.apache.spark.rdd.RDDOperationScope$.withScope(RDDOperationScope.scala:151)
	at org.apache.spark.rdd.RDDOperationScope$.withScope(RDDOperationScope.scala:112)
	at org.apache.spark.rdd.RDD.withScope(RDD.scala:414)
	at org.apache.spark.rdd.PairRDDFunctions.saveAsHadoopDataset(PairRDDFunctions.scala:1088)
	at org.apache.spark.rdd.PairRDDFunctions.$anonfun$saveAsHadoopFile$4(PairRDDFunctions.scala:1061)
	at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:23)
	at org.apache.spark.rdd.RDDOperationScope$.withScope(RDDOperationScope.scala:151)
	at org.apache.spark.rdd.RDDOperationScope$.withScope(RDDOperationScope.scala:112)
	at org.apache.spark.rdd.RDD.withScope(RDD.scala:414)
	at org.apache.spark.rdd.PairRDDFunctions.saveAsHadoopFile(PairRDDFunctions.scala:1026)
	at org.apache.spark.rdd.PairRDDFunctions.$anonfun$saveAsHadoopFile$3(PairRDDFunctions.scala:1008)
	at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:23)
	at org.apache.spark.rdd.RDDOperationScope$.withScope(RDDOperationScope.scala:151)
	at org.apache.spark.rdd.RDDOperationScope$.withScope(RDDOperationScope.scala:112)
	at org.apache.spark.rdd.RDD.withScope(RDD.scala:414)
	at org.apache.spark.rdd.PairRDDFunctions.saveAsHadoopFile(PairRDDFunctions.scala:1007)
	at org.apache.spark.rdd.PairRDDFunctions.$anonfun$saveAsHadoopFile$2(PairRDDFunctions.scala:964)
	at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:23)
	at org.apache.spark.rdd.RDDOperationScope$.withScope(RDDOperationScope.scala:151)
	at org.apache.spark.rdd.RDDOperationScope$.withScope(RDDOperationScope.scala:112)
	at org.apache.spark.rdd.RDD.withScope(RDD.scala:414)
	at org.apache.spark.rdd.PairRDDFunctions.saveAsHadoopFile(PairRDDFunctions.scala:962)
	at org.apache.spark.rdd.RDD.$anonfun$saveAsTextFile$2(RDD.scala:1578)
	at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:23)
	at org.apache.spark.rdd.RDDOperationScope$.withScope(RDDOperationScope.scala:151)
	at org.apache.spark.rdd.RDDOperationScope$.withScope(RDDOperationScope.scala:112)
	at org.apache.spark.rdd.RDD.withScope(RDD.scala:414)
	at org.apache.spark.rdd.RDD.saveAsTextFile(RDD.scala:1578)
	at org.apache.spark.rdd.RDD.$anonfun$saveAsTextFile$1(RDD.scala:1564)
	at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:23)
	at org.apache.spark.rdd.RDDOperationScope$.withScope(RDDOperationScope.scala:151)
	at org.apache.spark.rdd.RDDOperationScope$.withScope(RDDOperationScope.scala:112)
	at org.apache.spark.rdd.RDD.withScope(RDD.scala:414)
	at org.apache.spark.rdd.RDD.saveAsTextFile(RDD.scala:1564)
	at org.apache.spark.api.java.JavaRDDLike.saveAsTextFile(JavaRDDLike.scala:551)
	at org.apache.spark.api.java.JavaRDDLike.saveAsTextFile$(JavaRDDLike.scala:550)
	at org.apache.spark.api.java.AbstractJavaRDDLike.saveAsTextFile(JavaRDDLike.scala:45)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at py4j.reflection.MethodInvoker.invoke(MethodInvoker.java:244)
	at py4j.reflection.ReflectionEngine.invoke(ReflectionEngine.java:357)
	at py4j.Gateway.invoke(Gateway.java:282)
	at py4j.commands.AbstractCommand.invokeMethod(AbstractCommand.java:132)
	at py4j.commands.CallCommand.execute(CallCommand.java:79)
	at py4j.ClientServerConnection.waitForCommands(ClientServerConnection.java:182)
	at py4j.ClientServerConnection.run(ClientServerConnection.java:106)
	at java.lang.Thread.run(Thread.java:750)
Caused by: java.lang.UnsatisfiedLinkError: org.apache.hadoop.io.nativeio.NativeIO$Windows.access0(Ljava/lang/String;I)Z
	at org.apache.hadoop.io.nativeio.NativeIO$Windows.access0(Native Method)
	at org.apache.hadoop.io.nativeio.NativeIO$Windows.access(NativeIO.java:793)
	at org.apache.hadoop.fs.FileUtil.canRead(FileUtil.java:1215)
	at org.apache.hadoop.fs.FileUtil.list(FileUtil.java:1420)
	at org.apache.hadoop.fs.RawLocalFileSystem.listStatus(RawLocalFileSystem.java:601)
	at org.apache.hadoop.fs.FileSystem.listStatus(FileSystem.java:1972)
	at org.apache.hadoop.fs.FileSystem.listStatus(FileSystem.java:2014)
	at org.apache.hadoop.fs.ChecksumFileSystem.listStatus(ChecksumFileSystem.java:761)
	at org.apache.hadoop.fs.FileSystem.listStatus(FileSystem.java:1972)
	at org.apache.hadoop.fs.FileSystem.listStatus(FileSystem.java:2014)
	at org.apache.hadoop.mapreduce.lib.output.FileOutputCommitter.getAllCommittedTaskPaths(FileOutputCommitter.java:334)
	at org.apache.hadoop.mapreduce.lib.output.FileOutputCommitter.commitJobInternal(FileOutputCommitter.java:404)
	at org.apache.hadoop.mapreduce.lib.output.FileOutputCommitter.commitJob(FileOutputCommitter.java:377)
	at org.apache.hadoop.mapred.FileOutputCommitter.commitJob(FileOutputCommitter.java:136)
	at org.apache.hadoop.mapred.OutputCommitter.commitJob(OutputCommitter.java:291)
	at org.apache.spark.internal.io.HadoopMapReduceCommitProtocol.commitJob(HadoopMapReduceCommitProtocol.scala:182)
	at org.apache.spark.internal.io.SparkHadoopWriter$.$anonfun$write$3(SparkHadoopWriter.scala:100)
	at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:23)
	at org.apache.spark.util.Utils$.timeTakenMs(Utils.scala:605)
	at org.apache.spark.internal.io.SparkHadoopWriter$.write(SparkHadoopWriter.scala:100)
	... 51 more

In [85]:
time=spark.read.load('TimeProvince.csv',format="csv",inferSchema=True,header=True)
time.show()

+----------+----+-----------------+---------+--------+--------+
|      date|time|         province|confirmed|released|deceased|
+----------+----+-----------------+---------+--------+--------+
|2020-01-20|  16|            Seoul|        0|       0|       0|
|2020-01-20|  16|            Busan|        0|       0|       0|
|2020-01-20|  16|            Daegu|        0|       0|       0|
|2020-01-20|  16|          Incheon|        1|       0|       0|
|2020-01-20|  16|          Gwangju|        0|       0|       0|
|2020-01-20|  16|          Daejeon|        0|       0|       0|
|2020-01-20|  16|            Ulsan|        0|       0|       0|
|2020-01-20|  16|           Sejong|        0|       0|       0|
|2020-01-20|  16|      Gyeonggi-do|        0|       0|       0|
|2020-01-20|  16|       Gangwon-do|        0|       0|       0|
|2020-01-20|  16|Chungcheongbuk-do|        0|       0|       0|
|2020-01-20|  16|Chungcheongnam-do|        0|       0|       0|
|2020-01-20|  16|     Jeollabuk-do|        0|       0|       0|
|2020-01-20|  16|     Jeollanam-do|        0|       0|       0|
|2020-01-20|  16| Gyeongsangbuk-do|        0|       0|       0|
|2020-01-20|  16| Gyeongsangnam-do|        0|       0|       0|
|2020-01-20|  16|          Jeju-do|        0|       0|       0|
|2020-01-21|  16|            Seoul|        0|       0|       0|
|2020-01-21|  16|            Busan|        0|       0|       0|
|2020-01-21|  16|            Daegu|        0|       0|       0|
+----------+----+-----------------+---------+--------+--------+
only showing top 20 rows

In [87]:
from pyspark.sql.window import Window

In [93]:
window_f=Window.partitionBy(['province']).orderBy('date')

In [95]:
time=time.withColumn('F_lag',F.lag(F.col('confirmed'),7).over(window_f))
time.show()

+----------+----+--------+---------+--------+--------+-----+
|      date|time|province|confirmed|released|deceased|F_lag|
+----------+----+--------+---------+--------+--------+-----+
|2020-01-20|  16|   Busan|        0|       0|       0| null|
|2020-01-21|  16|   Busan|        0|       0|       0| null|
|2020-01-22|  16|   Busan|        0|       0|       0| null|
|2020-01-23|  16|   Busan|        0|       0|       0| null|
|2020-01-24|  16|   Busan|        0|       0|       0| null|
|2020-01-25|  16|   Busan|        0|       0|       0| null|
|2020-01-26|  16|   Busan|        0|       0|       0| null|
|2020-01-27|  16|   Busan|        0|       0|       0|    0|
|2020-01-28|  16|   Busan|        0|       0|       0|    0|
|2020-01-29|  16|   Busan|        0|       0|       0|    0|
|2020-01-30|  16|   Busan|        0|       0|       0|    0|
|2020-01-31|  16|   Busan|        0|       0|       0|    0|
|2020-02-01|  16|   Busan|        0|       0|       0|    0|
|2020-02-02|  16|   Busan|        0|       0|       0|    0|
|2020-02-03|  16|   Busan|        0|       0|       0|    0|
|2020-02-04|  16|   Busan|        0|       0|       0|    0|
|2020-02-05|  16|   Busan|        0|       0|       0|    0|
|2020-02-06|  16|   Busan|        0|       0|       0|    0|
|2020-02-07|  16|   Busan|        0|       0|       0|    0|
|2020-02-08|  16|   Busan|        0|       0|       0|    0|
+----------+----+--------+---------+--------+--------+-----+
only showing top 20 rows

In [1]:
import findspark
findspark.init()

In [2]:
import pyspark
from pyspark.sql import SparkSession

In [3]:
spark=SparkSession.builder.appName('pi').getOrCreate()

In [4]:
spark

In [5]:
import numpy as np
rdd=spark.sparkContext.parallelize(np.arange(0,20,2),4)
rdd.collect()

[0, 2, 4, 6, 8, 10, 12, 14, 16, 18]

In [6]:
rdd.getNumPartitions()

4

In [7]:
rdd.glom().collect()

[[0, 2], [4, 6], [8, 10], [12, 14, 16, 18]]

In [8]:
rdd.first()

0

In [9]:
rdd.filter(lambda x:x>3).collect()

[4, 6, 8, 10, 12, 14, 16, 18]

In [10]:
text=spark.sparkContext.textFile('FIFA-21 Complete.csv')
text.collect()

['player_id;name;nationality;position;overall;age;hits;potential;team',
 '158023;Lionel Messi;Argentina;ST|CF|RW;94;33;299;94;"FC Barcelona "',
 '20801;Cristiano Ronaldo;Portugal;ST|LW;93;35;276;93;"Juventus "',
 '190871;Neymar Jr;Brazil;CAM|LW;92;28;186;92;"Paris Saint-Germain "',
 '203376;Virgil van Dijk;Netherlands;CB;91;29;127;92;"Liverpool "',
 '200389;Jan Oblak;Slovenia;GK;91;27;47;93;"Atlético Madrid "',
 '192985;Kevin De Bruyne;Belgium;CM|CAM;91;29;119;91;"Manchester City "',
 '188545;Robert Lewandowski;Poland;ST;91;31;89;91;"FC Bayern München "',
 '183277;Eden Hazard;Belgium;ST|LW;91;29;66;91;"Real Madrid "',
 '212831;Alisson;Brazil;GK;90;27;53;91;"Liverpool "',
 '209331;Mohamed Salah;Egypt;ST|RW;90;28;94;90;"Liverpool "',
 '208722;Sadio Mané;Senegal;LW;90;28;76;90;"Liverpool "',
 '192448;Marc-André ter Stegen;Germany;GK;90;28;68;93;"FC Barcelona "',
 '153079;Sergio Agüero;Argentina;ST;90;32;50;90;"Manchester City "',
 '231747;Kylian Mbappé;France;ST|RW|LW;89;21;222;95;"Paris Saint-Germain "',
 '215914;N\'Golo Kanté;France;CDM|CM;89;29;75;89;"Chelsea "',
 '202126;Harry Kane;England;ST;89;27;64;91;"Tottenham Hotspur "',
 '194765;Antoine Griezmann;France;ST|CF|LW;89;29;66;89;"FC Barcelona "',
 '182521;Toni Kroos;Germany;CM;89;30;37;89;"Real Madrid "',
 '177003;Luka Modric;Croatia;CM;89;34;31;89;"Real Madrid "',
 '176580;Luis Suárez;Uruguay;ST;89;33;54;89;"FC Barcelona "',
 '167495;Manuel Neuer;Germany;GK;89;34;42;89;"FC Bayern München "',
 '155862;Sergio Ramos;Spain;CB;89;34;55;89;"Real Madrid "',
 '210257;Ederson;Brazil;GK;88;26;40;91;"Manchester City "',
 '202652;Raheem Sterling;England;RW|LW;88;25;61;90;"Manchester City "',
 '201942;Roberto Firmino;Brazil;CF;88;28;79;88;"Liverpool "',
 '201024;Kalidou Koulibaly;Senegal;CB;88;29;78;90;"Napoli "',
 '200145;Casemiro;Brazil;CDM;88;28;37;89;"Real Madrid "',
 '193080;De Gea;Spain;GK;88;29;39;88;"Manchester United "',
 '192119;Thibaut Courtois;Belgium;GK;88;28;34;89;"Real Madrid "',
 '189511;Sergio Busquets;Spain;CDM;88;32;34;88;"FC Barcelona "',
 '188567;Pierre-Emerick Aubameyang;Gabon;ST|LM;88;31;114;88;"Arsenal "',
 '165153;Karim Benzema;France;ST|CF;88;32;51;88;"Real Madrid "',
 '162835;Samir Handanovic;Slovenia;GK;88;36;13;88;"Inter "',
 '152729;Piqué;Spain;CB;88;33;41;88;"FC Barcelona "',
 '138956;Giorgio Chiellini;Italy;CB;88;35;19;88;"Juventus "',
 '218667;Bernardo Silva;Portugal;CM|CAM|RW;87;25;53;90;"Manchester City "',
 '212622;Joshua Kimmich;Germany;RB|CDM|CM;87;25;82;90;"FC Bayern München "',
 '212218;Aymeric Laporte;France;CB;87;26;38;90;"Manchester City "',
 '211110;Paulo Dybala;Argentina;CAM|CF;87;26;95;90;"Juventus "',
 '200104;Heung Min Son;Korea Republic;LM|CF;87;28;75;87;"Tottenham Hotspur "',
 '199556;Marco Verratti;Italy;CDM|CM;87;27;45;88;"Paris Saint-Germain "',
 '195864;Paul Pogba;France;CDM|CM;87;27;70;88;"Manchester United "',
 '193041;Keylor Navas;Costa Rica;GK;87;33;28;87;"Paris Saint-Germain "',
 '192387;Ciro Immobile;Italy;ST;87;30;130;87;"Lazio "',
 '190460;Christian Eriksen;Denmark;RM|CM|CAM;87;28;48;87;"Inter "',
 '189513;Parejo;Spain;CM;87;31;14;87;"Valencia CF "',
 '188350;Marco Reus;Germany;CAM|CF;87;31;42;87;"Borussia Dortmund "',
 '186153;Wojciech Szczesny;Poland;GK;87;30;17;88;"Juventus "',
 '183898;Ángel Di María;Argentina;RW|LW;87;32;41;87;"Paris Saint-Germain "',
 '182493;Diego Godín;Uruguay;CB;87;34;16;87;"Inter "',
 '178603;Mats Hummels;Germany;CB;87;31;18;87;"Borussia Dortmund "',
 '175943;Dries Mertens;Belgium;ST|CF;87;33;34;87;"Napoli "',
 '168542;David Silva;Spain;CM|CAM;87;34;28;87;"Manchester City "',
 '167948;Hugo Lloris;France;GK;87;33;19;87;"Tottenham Hotspur "',
 '164240;Thiago Silva;Brazil;CB;87;35;28;87;"Paris Saint-Germain "',
 '233049;Jadon Sancho;England;RM|LM|CAM;86;20;300;94;"Borussia Dortmund "',
 '232363;Milan Škriniar;Slovakia;CB;86;25;62;90;"Inter "',
 '228702;Frenkie de Jong;Netherlands;CM;86;23;126;92;"FC Barcelona "',
 '222492;Leroy Sané;Germany;LW;86;24;74;90;"Manchester City "',
 '220440;Clément Lenglet;France;CB;86;25;58;90;"FC Barcelona "',
 '216267;Andrew Robertson;Scotland;LB;86;26;66;89;"Liverpool "',
 '212198;Bruno Fernandes;Portugal;CM|CAM;86;25;127;89;"Manchester United "',
 '212188;Timo Werner;Germany;ST;86;24;136;89;"RB Leipzig "',
 '209499;Fabinho;Brazil;CDM;86;26;44;88;"Liverpool "',
 '208830;Jamie Vardy;England;ST;86;33;43;86;"Leicester City "',
 '208670;Hakim Ziyech;Morocco;CAM|RW;86;27;113;87;"Ajax "',
 '207865;Marquinhos;Brazil;CB|CDM;86;26;48;90;"Paris Saint-Germain "',
 '204485;Riyad Mahrez;Algeria;RM|RW;86;29;40;86;"Manchester City "',
 '201535;Raphaël Varane;France;CB;86;27;39;89;"Real Madrid "',
 '201399;Mauro Icardi;Argentina;ST;86;27;47;87;"Paris Saint-Germain "',
 '198219;Lorenzo Insigne;Italy;LM|CF|LW;86;29;42;86;"Napoli "',
 '193747;Koke;Spain;RM|LM|CM;86;28;15;86;"Atlético Madrid "',
 '192505;Romelu Lukaku;Belgium;ST;86;27;63;87;"Inter "',
 '189509;Thiago;Spain;CDM|CM;86;29;47;86;"FC Bayern München "',
 '189332;Jordi Alba;Spain;LB;86;31;35;86;"FC Barcelona "',
 '184344;Leonardo Bonucci;Italy;CB;86;33;17;86;"Juventus "',
 '184087;Toby Alderweireld;Belgium;CB;86;31;16;86;"Tottenham Hotspur "',
 '180206;Miralem Pjanic;Bosnia & Herzegovina;CDM|CM;86;30;31;86;"Juventus "',
 '179813;Edinson Cavani;Uruguay;ST;86;33;26;86;"Paris Saint-Germain "',
 '177683;Yann Sommer;Switzerland;GK;86;31;5;86;"Borussia Mönchengladbach "',
 '143076;Alejandro Gómez;Argentina;ST|CAM|CF;86;32;49;86;"Atalanta "',
 '235243;Matthijs de Ligt;Netherlands;CB;85;20;110;92;"Juventus "',
 '231866;Rodri;Spain;CDM|CM;85;24;36;89;"Manchester City "',
 '231281;Trent Alexander-Arnold;England;RB;85;21;135;90;"Liverpool "',
 '230658;Arthur;Brazil;CM;85;23;64;90;"FC Barcelona "',
 '230621;Gianluigi Donnarumma;Italy;GK;85;21;62;92;"Milan "',
 '226753;André Onana;Cameroon;GK;85;24;55;89;"Ajax "',
 '223848;Sergej Milinkovic-Savic;Serbia;CDM|CM|CAM;85;25;55;90;"Lazio "',
 '216594;Nabil Fekir;France;ST|RM|CAM;85;27;34;87;"Real Betis "',
 '216460;José María Giménez;Uruguay;CB;85;25;34;89;"Atlético Madrid "',
 '212190;Niklas Süle;Germany;CB;85;24;42;90;"FC Bayern München "',
 '208421;Saúl;Spain;LB|LM|CM;85;25;39;89;"Atlético Madrid "',
 '206113;Serge Gnabry;Germany;RM|LM|RW;85;25;79;87;"FC Bayern München "',
 '205600;Samuel Umtiti;France;CB;85;26;42;88;"FC Barcelona "',
 '204963;Carvajal;Spain;RB;85;28;24;85;"Real Madrid "',
 '198706;Luis Alberto;Spain;CM|CAM|CF;85;27;27;86;"Lazio "',
 '198176;Stefan de Vrij;Netherlands;CB;85;28;19;86;"Inter "',
 '197965;Pizzi;Portugal;RM|CM;85;30;14;85;"SL Benfica "',
 '197781;Isco;Spain;CM|CAM|LW;85;28;25;85;"Real Madrid "',
 '192629;Iago Aspas;Spain;ST|RW;85;32;10;85;"RC Celta "',
 '192563;Bernd Leno;Germany;GK;85;28;30;87;"Arsenal "',
 '189596;Thomas Müller;Germany;RM|CAM|RW;85;30;23;85;"FC Bayern München "',
 '189242;Coutinho;Brazil;CM|CAM|LW;85;28;49;85;"FC Bayern München "',
 '189117;Roman Bürki;Switzerland;GK;85;29;10;86;"Borussia Dortmund "',
 '187961;Paulinho;Brazil;CDM|CM|CAM;85;32;22;85;"Guangzhou Evergrande Taobao FC "',
 '185122;Péter Gulácsi;Hungary;GK;85;30;14;86;"RB Leipzig "',
 '183711;Jordan Henderson;England;CDM|CM;85;30;41;85;"Liverpool "',
 '181291;Georginio Wijnaldum;Netherlands;CDM|CM;85;29;40;85;"Liverpool "',
 '177413;Axel Witsel;Belgium;CDM|CM;85;31;26;85;"Borussia Dortmund "',
 '173731;Gareth Bale;Wales;ST|RW|LW;85;31;69;85;"Real Madrid "',
 '172871;Jan Vertonghen;Belgium;LB|CB;85;33;26;85;"Tottenham Hotspur "',
 '168651;Ivan Rakitic;Croatia;CM;85;32;38;85;"FC Barcelona "',
 '167664;Gonzalo Higuaín;Argentina;ST;85;32;24;85;"Juventus "',
 '135507;Fernandinho;Brazil;CB|CDM;85;35;14;85;"Manchester City "',
 '41236;Zlatan Ibrahimovic;Sweden;ST;85;38;189;85;"Milan "',
 '235790;Kai Havertz;Germany;RM|CAM;84;21;176;93;"Bayer 04 Leverkusen "',
 '231677;Marcus Rashford;England;ST|LM;84;22;104;89;"Manchester United "',
 '231478;Lautaro Martínez;Argentina;ST;84;22;138;91;"Inter "',
 '226790;Wilfred Ndidi;Nigeria;CDM|CM;84;23;36;88;"Leicester City "',
 '220814;Lucas Hernández;France;LB|CB;84;24;47;89;"FC Bayern München "',
 '213345;Kingsley Coman;France;RM|LM|LW;84;24;65;88;"FC Bayern München "',
 '212462;Alex Telles;Brazil;LB;84;27;42;85;"FC Porto "',
 '212194;Julian Brandt;Germany;LM|CM|CAM;84;24;51;88;"Borussia Dortmund "',
 '210243;Ricardo Pereira;Portugal;RB;84;26;28;86;"Leicester City "',
 '209989;Thomas Partey;Ghana;CDM|CM;84;27;42;87;"Atlético Madrid "',
 '209658;Leon Goretzka;Germany;CDM|CM|CAM;84;25;58;88;"FC Bayern München "',
 '207863;Felipe;Brazil;CB;84;31;19;84;"Atlético Madrid "',
 '207410;Mateo Kovacic;Croatia;CM;84;26;43;87;"Chelsea "',
 '205498;Jorginho;Italy;CDM|CM;84;28;29;84;"Chelsea "',
 '202556;Memphis Depay;Netherlands;CAM|CF|LW;84;26;75;87;"Olympique Lyonnais "',
 '200647;Josip Ilicic;Slovenia;ST|CF;84;32;41;84;"Atalanta "',
 '199914;Allan;Brazil;CM;84;29;13;84;"Napoli "',
 '199845;Francesco Acerbi;Italy;CB;84;32;15;84;"Lazio "',
 '199482;Anthony Lopes;Portugal;GK;84;29;5;86;"Olympique Lyonnais "',
 '199451;Wissam Ben Yedder;France;ST;84;29;31;84;"AS Monaco Football Club SA "',
 '198710;James Rodríguez;Colombia;RM|CM|CAM;84;29;41;84;"Real Madrid "',
 '194404;Neto;Brazil;GK;84;31;7;85;"FC Barcelona "',
 '193474;Idrissa Gueye;Senegal;CDM|CM;84;30;30;84;"Paris Saint-Germain "',
 '193301;Alexandre Lacazette;France;ST;84;29;43;84;"Arsenal "',
 '192774;Kostas Manolas;Greece;CB;84;29;11;85;"Napoli "',
 '191043;Alex Sandro;Brazil;LB|LM;84;29;18;84;"Juventus "',
 '190483;Douglas Costa;Brazil;LM|RW|LW;84;29;24;84;"Juventus "',
 '190286;Canales;Spain;LM|CM|CAM;84;29;18;84;"Real Betis "',
 '188152;Oscar;Brazil;CM|CAM|LW;84;28;25;84;"Shanghai SIPG FC "',
 '186942;Ilkay Gündogan;Germany;CDM|CM;84;29;18;84;"Manchester City "',
 '185020;José Callejón;Spain;RM|RW;84;33;13;84;"Napoli "',
 '184432;Azpilicueta;Spain;RB|LB|CB;84;30;25;84;"Chelsea "',
 '181872;Arturo Vidal;Chile;CDM|CM|CAM;84;33;53;84;"FC Barcelona "',
 '180930;Edin Dzeko;Bosnia & Herzegovina;ST;84;34;13;84;"Roma "',
 '178562;Éver Banega;Argentina;CDM|CM;84;32;9;84;"Sevilla FC "',
 '178518;Radja Nainggolan;Belgium;CM|CAM|CF;84;32;19;84;"Cagliari "',
 '176676;Marcelo;Brazil;LB;84;32;22;84;"Real Madrid "',
 '176266;Lucas Leiva;Brazil;CDM;84;33;10;84;"Lazio "',
 '170890;Blaise Matuidi;France;CDM|CM;84;33;20;84;"Juventus "',
 '168435;Salvatore Sirigu;Italy;GK;84;33;6;84;"Torino "',
 '162347;João Moutinho;Portugal;CM;84;33;12;84;"Wolverhampton Wanderers "',
 '231443;Ousmane Dembélé;France;RW|LW;83;23;82;90;"FC Barcelona "',
 '230481;Ronaldo Cabrais;Brazil;CAM|RW;83;28;22;83;"Grêmio "',
 '230375;Josué Chiamulera;Brazil;CB;83;28;12;83;"Grêmio "',
 '230294;Louri Beretta;Brazil;ST|CF;83;28;15;83;"Atlético Mineiro "',
 '230142;Oyarzabal;Spain;RW|LW;83;23;22;89;"Real Sociedad "',
 '226271;Fabián;Spain;CM;83;24;32;89;"Napoli "',
 '221363;Donny van de Beek;Netherlands;CM|CAM;83;23;72;87;"Ajax "',
 '221087;Pau López;Spain;GK;83;25;12;88;"Roma "',
 '217940;Dakonam Djené;Togo;CB;83;28;6;84;"Getafe CF "',
 '216547;Rafa;Portugal;RM|LM;83;27;10;84;"SL Benfica "',
 '216354;Andrej Kramaric;Croatia;ST|CAM;83;29;10;83;"TSG 1899 Hoffenheim "',
 '216352;Marcelo Brozovic;Croatia;CDM|CM;83;27;18;85;"Inter "',
 '215333;Duván Zapata;Colombia;ST;83;29;45;83;"Atalanta "',
 '212523;Anderson Talisca;Brazil;CAM|RW;83;26;21;86;"Guangzhou Evergrande Taobao FC "',
 '212151;Thomas Strakosha;lbania;GK;83;25;16;88;"Lazio "',
 '211300;Anthony Martial;France;ST;83;24;72;87;"Manchester United "',
 '211256;Nicolás Tagliafico;Argentina;LB;83;27;28;84;"Ajax "',
 '211117;Dele Alli;England;CM|CAM;83;24;52;88;"Tottenham Hotspur "',
 '210413;Alessio Romagnoli;Italy;CB;83;25;49;89;"Milan "',
 '210035;Grimaldo;Spain;LB;83;24;34;87;"SL Benfica "',
 '209889;Raphaël Guerreiro;Portugal;LB|LM|CM;83;26;27;84;"Borussia Dortmund "',
 '208808;Quincy Promes;Netherlands;CAM|LW;83;28;22;83;"Ajax "',
 '208574;Filip Kostic;Serbia;LWB|LM|LW;83;27;16;83;"Eintracht Frankfurt "',
 '208418;Yannick Carrasco;Belgium;LM;83;26;25;84;"Atlético Madrid "',
 '206585;Kepa;Spain;GK;83;25;60;87;"Chelsea "',
 '205678;Edin Višca;Bosnia & Herzegovina;RM;83;30;8;83;"Medipol Basaksehir FK "',
 '205175;Arkadiusz Milik;Poland;ST;83;26;25;86;"Napoli "',
 '205070;Portu;Spain;RM|CF|RW;83;28;6;83;"Real Sociedad "',
 '204970;Florian Thauvin;France;RM|RW;83;27;16;83;"Olympique de Marseille "',
 '204923;Marcel Sabitzer;Austria;CM|CAM;83;26;20;85;"RB Leipzig "',
 '204838;Raúl Jiménez;Mexico;ST;83;29;63;83;"Wolverhampton Wanderers "',
 '204639;Stefan Savic;Montenegro;CB;83;29;12;84;"Atlético Madrid "',
 '203486;Thorgan Hazard;Belgium;RM|LM|CF;83;27;28;83;"Borussia Dortmund "',
 '203263;Harry Maguire;England;CB;83;27;48;86;"Manchester United "',
 '201305;Gabriel Paulista;Brazil;CB;83;29;14;84;"Valencia CF "',
 '201153;Morata;Spain;ST;83;27;10;84;"Atlético Madrid "',
 '200458;Lucas Digne;France;LB;83;27;18;86;"Everton "',
 '199434;Dušan Tadic;Serbia;CAM|CF|LW;83;31;12;83;"Ajax "',
 '199042;Charles Aránguiz;Chile;CDM|CM;83;31;15;83;"Bayer 04 Leverkusen "',
 '198950;Pablo Sarabia;Spain;CAM|RW;83;28;33;84;"Paris Saint-Germain "',
 '198717;Wilfried Zaha;Ivory Coast;LM|CF;83;27;54;83;"Crystal Palace "',
 '198329;Rodrigo;Spain;ST;83;29;17;83;"Valencia CF "',
 '198141;Bartra;Spain;CB|CDM;83;29;18;84;"Real Betis "',
 '197445;David Alaba;Austria;LB|CB;83;28;46;84;"FC Bayern München "',
 '197061;Joel Matip;Cameroon;CB;83;28;14;84;"Liverpool "',
 '193082;Juan Cuadrado;Colombia;RB|RM|RW;83;32;21;83;"Juventus "',
 '192984;Koen Casteels;Belgium;GK;83;28;3;85;"VfL Wolfsburg "',
 '190941;Lukáš Hrádecky;Finland;GK;83;30;8;83;"Bayer 04 Leverkusen "',
 '190815;Daley Blind;Netherlands;LB|CB|CDM;83;30;20;83;"Ajax "',
 '189575;Muniain;Spain;CAM|RW|LW;83;27;9;83;"Athletic Club "',
 '188943;Kevin Trapp;Germany;GK;83;30;11;83;"Eintracht Frankfurt "',
 '188377;Kyle Walker;England;RB;83;30;29;83;"Manchester City "',
 '186561;Aaron Ramsey;Wales;CM|CAM;83;29;14;83;"Juventus "',
 '184200;Marko Arnautovic;Austria;ST;83;31;9;83;"Shanghai SIPG FC "',
 '183574;Max Kruse;Germany;ST|CAM;83;32;5;83;"Fenerbahçe SK "',
 '181458;Ivan Perišic;Croatia;LM|LW;83;31;13;83;"FC Bayern München "',
 '179846;Sami Khedira;Germany;CDM|CM;83;33;19;83;"Juventus "',
 '178005;Rui Patrício;Portugal;GK;83;32;19;83;"Wolverhampton Wanderers "',
 '176635;Mesut Özil;Germany;CAM|RW;83;31;44;83;"Arsenal "',
 '171877;Marek Hamšík;Slovakia;CDM|CM|CAM;83;33;12;83;"Dalian YiFang FC "',
 '170481;Ezequiel Garay;Argentina;CB;83;33;5;83;"Valencia CF "',
 '169416;Carlos Vela;Mexico;CAM|RW|LW;83;31;20;83;"LAFC "',
 '163705;Steve Mandanda;France;GK;83;35;4;83;"Olympique de Marseille "',
 '163587;Kasper Schmeichel;Denmark;GK;83;33;41;83;"Leicester City "',
 '157481;Raúl Albiol;Spain;CB;83;34;7;83;"Villarreal CF "',
 '146562;Santi Cazorla;Spain;CDM|LM|CM;83;35;22;83;"Villarreal CF "',
 '1179;Gianluigi Buffon;Italy;GK;83;42;50;83;"Juventus "',
 '245313;José María Sildero;Uruguay;RM|CAM;82;28;17;82;"Free Agents "',
 '245309;Egidio Maestre Schetino;Uruguay;CB;82;28;12;82;"Free Agents "',
 '239818;Rúben Dias;Portugal;CB;82;23;35;88;"SL Benfica "',
 '239053;Federico Valverde;Uruguay;CDM|CM;82;22;87;90;"Real Madrid "',
 '236583;Jirí Pavlenka;Czech Republic;GK;82;28;3;83;"SV Werder Bremen "',
 '235212;Achraf Hakimi;Morocco;RB|LB|RM;82;21;91;87;"Borussia Dortmund "',
 '232432;Luka Jovic;Serbia;ST;82;22;46;88;"Real Madrid "',
 '230666;Gabriel Jesus;Brazil;ST;82;23;48;88;"Manchester City "',
 '230430;Oswaldinato;Brazil;ST;82;28;20;82;"Flamengo "',
 '230384;Nuno Padrenda;Brazil;ST|CAM|CF;82;24;6;84;"Palmeiras "',
 '230258;Rosberto Dourado;Brazil;CDM|CM|CAM;82;20;13;82;"Atlético Mineiro "',
 '230225;Juiano Mestres;Brazil;CB|CDM;82;24;6;82;"Cruzeiro "',
 '230168;Raphaelito Anjos;Brazil;GK;82;32;3;82;"Grêmio "',
 '229880;Aaron Wan-Bissaka;England;RWB|RB|RW;82;22;94;89;"Manchester United "',
 '229261;Denis Zakaria;Switzerland;CB|CDM|CM;82;23;29;86;"Borussia Mönchengladbach "',
 '227928;Nélson Semedo;Portugal;RB;82;26;51;85;"FC Barcelona "',
 '226226;Giovani Lo Celso;Argentina;CM|CAM;82;24;31;87;"Tottenham Hotspur "',
 '226110;Nicolas Pépé;Ivory Coast;RM|RW;82;25;79;87;"Arsenal "',
 '225953;Steven Bergwijn;Netherlands;CAM|RW|LW;82;22;44;87;"Tottenham Hotspur "',
 '225850;Presnel Kimpembe;France;CB;82;24;46;86;"Paris Saint-Germain "',
 '225100;Joe Gomez;England;RB|CB;82;23;66;89;"Liverpool "',
 '224411;Gonçalo Guedes;Portugal;ST|LM;82;23;25;88;"Valencia CF "',
 '224334;Marcos Acuña;Argentina;LB|LW;82;28;12;82;"Sporting CP "',
 '224293;Rúben Neves;Portugal;CM;82;23;32;87;"Wolverhampton Wanderers "',
 '223952;David Soria;Spain;GK;82;27;5;84;"Getafe CF "',
 '222665;Martin Ødegaard;Norway;RM|CM|CAM;82;21;68;88;"Real Sociedad "',
 '220971;Naby Keïta;Guinea;CDM|CM;82;25;20;86;"Liverpool "',
 '220834;Marco Asensio;Spain;RW|LW;82;24;47;86;"Real Madrid "',
 '220793;Davinson Sánchez;Colombia;CB;82;24;23;85;"Tottenham Hotspur "',
 '220697;James Maddison;England;CM|CAM|LW;82;23;64;87;"Leicester City "',
 '220407;Martin Dúbravka;Slovakia;GK;82;31;3;82;"Newcastle United "',
 '219683;Corentin Tolisso;France;CDM|CM;82;25;38;85;"FC Bayern München "',
 '216409;Matteo Politano;Italy;ST|RM|RW;82;26;23;83;"Napoli "',
 '216201;Iñaki Williams;Spain;ST|RW;82;26;45;85;"Athletic Club "',
 '215698;Mike Maignan;France;GK;82;25;18;86;"LOSC Lille "',
 '214997;Ángel Correa;Argentina;ST|RM;82;25;34;85;"Atlético Madrid "',
 '213565;Thomas Lemar;France;RM|LM|CAM;82;24;31;86;"Atlético Madrid "',
 '211591;Moussa Dembélé;France;ST;82;24;23;86;"Olympique Lyonnais "',
 '210514;João Cancelo;Portugal;RB;82;26;43;86;"Manchester City "',
 '210008;Adrien Rabiot;France;CDM|CM;82;25;32;85;"Juventus "',
 '209960;Pacheco;Spain;GK;82;28;3;84;"D. Alavés "',
 '208596;Andrea Belotti;Italy;ST;82;26;28;85;"Torino "',
 '208333;Emre Can;Germany;CDM|CM;82;26;24;85;"Borussia Dortmund "',
 '208093;Gerard Moreno;Spain;ST|RM;82;28;14;82;"Villarreal CF "',
 '207877;Josef Martínez;Venezuela;ST;82;27;27;84;"Atlanta United "',
 '207862;Matthias Ginter;Germany;CB;82;26;25;83;"Borussia Mönchengladbach "',
 '207566;William Carvalho;Portugal;CDM|CM;82;28;13;82;"Real Betis "',
 '205693;Sébastien Haller;France;ST;82;26;16;84;"West Ham United "',
 '205452;Antonio Rüdiger;Germany;CB;82;27;24;84;"Chelsea "',
 '202857;Karim Bellarabi;Germany;RM;82;30;5;82;"Bayer 04 Leverkusen "',
 '202166;Julian Draxler;Germany;CM|CAM|LW;82;26;31;83;"Paris Saint-Germain "',
 '201995;Felipe Anderson;Brazil;LM|CAM;82;27;14;82;"West Ham United "',
 '200949;Lucas Moura;Brazil;RM|CF;82;27;25;82;"Tottenham Hotspur "',
 '200888;Danilo Pereira;Portugal;CDM|CM;82;28;9;82;"FC Porto "',
 '200724;Nacho Fernández;Spain;RB|LB|CB;82;30;13;82;"Real Madrid "',
 '200610;Kevin Volland;Germany;ST|RW|LW;82;27;8;83;"Bayer 04 Leverkusen "',
 '200454;Paco Alcácer;Spain;ST;82;26;16;84;"Villarreal CF "',
 '199987;Jasper Cillessen;Netherlands;GK;82;31;15;82;"Valencia CF "',
 '199564;Sergi Roberto;Spain;RB|CM;82;28;28;82;"FC Barcelona "',
 '198951;Cédric Bakambu;DR Congo;ST;82;29;8;82;"Beijing Sinobo Guoan FC "',
 '198009;Mattia Perin;Italy;GK;82;27;12;84;"Genoa "',
 '195093;Willian José;Brazil;ST;82;28;5;82;"Real Sociedad "',
 '193698;Oliver Baumann;Germany;GK;82;30;1;83;"TSG 1899 Hoffenheim "',
 '193525;Mário Fernandes;Russia;RWB|RM|RW;82;29;16;82;"PFC CSKA Moscow "',
 '193283;Thomas Delaney;Denmark;CDM|CM;82;28;13;83;"Borussia Dortmund "',
 '193165;Jesús Corona;Mexico;RB|RM;82;27;21;83;"FC Porto "',
 '193105;Alphonse Areola;France;GK;82;27;18;86;"Real Madrid "',
 '190584;Illarramendi;Spain;CDM|CM;82;30;4;82;"Real Sociedad "',
 '188803;Taison;Brazil;LM|CAM;82;32;11;82;"Shakhtar Donetsk "',
 '185103;Aleksandar Kolarov;Serbia;LB;82;34;14;82;"Roma "',
 '184134;Fernando;Brazil;CDM|CM;82;33;9;82;"Sevilla FC "',
 '182494;Fernando Muslera;Uruguay;GK;82;34;6;82;"Galatasaray SK "',
 '180403;Willian;Brazil;RM|RW|LW;82;31;53;82;"Chelsea "',
 '179844;Diego Costa;Spain;ST;82;31;20;82;"Atlético Madrid "',
 '178750;Sergio Asenjo;Spain;GK;82;31;2;83;"Villarreal CF "',
 '177610;Javi Martínez;Spain;CB|CDM;82;31;18;82;"FC Bayern München "',
 '177388;Dimitri Payet;France;CAM|LW;82;33;13;82;"Olympique de Marseille "',

In [11]:
text=spark.sparkContext.textFile('lab3.txt')
text.collect()

["Big Data refers to a massive set of data that no conventional data management tool can handle. Big Data is therefore a concept that allows access to gigantic databases in real time. Big Data's main objectives are to improve a company's or system's responsiveness to a large amount of data collected, increase productivity and refine knowledge of customer behavior, so that it can offer personalized offers or advertisements and create new trends.",
 'The Internet of Things (IoT) is a concept that connects physical or virtual objects to the internet. The technology very often used is the sensor, allowing to link a physical object such as a watch, a drone or even a speaker, to the internet. If for a long time the few objects connected to the Internet were the telephone and the computer, this is no longer the case today and every year new types of objects incorporating IOT technology are born. IOT is one of the greatest technological revolutions of our era and its potential for exploitation is immense. IOT could have a huge impact on the cars of the future or on the new versions of smart-cities, an urban space connected to the Internet, thus significantly improving the lives of users, while reducing the negative impact of these on the planet. ']

In [12]:
def fun(line):
    line=line.lower()
    line=line.split()
    return line


rdd2=text.map(fun)
rdd2.collect()

[['big',
  'data',
  'refers',
  'to',
  'a',
  'massive',
  'set',
  'of',
  'data',
  'that',
  'no',
  'conventional',
  'data',
  'management',
  'tool',
  'can',
  'handle.',
  'big',
  'data',
  'is',
  'therefore',
  'a',
  'concept',
  'that',
  'allows',
  'access',
  'to',
  'gigantic',
  'databases',
  'in',
  'real',
  'time.',
  'big',
  "data's",
  'main',
  'objectives',
  'are',
  'to',
  'improve',
  'a',
  "company's",
  'or',
  "system's",
  'responsiveness',
  'to',
  'a',
  'large',
  'amount',
  'of',
  'data',
  'collected,',
  'increase',
  'productivity',
  'and',
  'refine',
  'knowledge',
  'of',
  'customer',
  'behavior,',
  'so',
  'that',
  'it',
  'can',
  'offer',
  'personalized',
  'offers',
  'or',
  'advertisements',
  'and',
  'create',
  'new',
  'trends.'],
 ['the',
  'internet',
  'of',
  'things',
  '(iot)',
  'is',
  'a',
  'concept',
  'that',
  'connects',
  'physical',
  'or',
  'virtual',
  'objects',
  'to',
  'the',
  'internet.',
  'the',
  'technology',
  'very',
  'often',
  'used',
  'is',
  'the',
  'sensor,',
  'allowing',
  'to',
  'link',
  'a',
  'physical',
  'object',
  'such',
  'as',
  'a',
  'watch,',
  'a',
  'drone',
  'or',
  'even',
  'a',
  'speaker,',
  'to',
  'the',
  'internet.',
  'if',
  'for',
  'a',
  'long',
  'time',
  'the',
  'few',
  'objects',
  'connected',
  'to',
  'the',
  'internet',
  'were',
  'the',
  'telephone',
  'and',
  'the',
  'computer,',
  'this',
  'is',
  'no',
  'longer',
  'the',
  'case',
  'today',
  'and',
  'every',
  'year',
  'new',
  'types',
  'of',
  'objects',
  'incorporating',
  'iot',
  'technology',
  'are',
  'born.',
  'iot',
  'is',
  'one',
  'of',
  'the',
  'greatest',
  'technological',
  'revolutions',
  'of',
  'our',
  'era',
  'and',
  'its',
  'potential',
  'for',
  'exploitation',
  'is',
  'immense.',
  'iot',
  'could',
  'have',
  'a',
  'huge',
  'impact',
  'on',
  'the',
  'cars',
  'of',
  'the',
  'future',
  'or',
  'on',
  'the',
  'new',
  'versions',
  'of',
  'smart-cities,',
  'an',
  'urban',
  'space',
  'connected',
  'to',
  'the',
  'internet,',
  'thus',
  'significantly',
  'improving',
  'the',
  'lives',
  'of',
  'users,',
  'while',
  'reducing',
  'the',
  'negative',
  'impact',
  'of',
  'these',
  'on',
  'the',
  'planet.']]

In [13]:
rdd3=text.flatMap(fun)
rdd3.collect()

['big',
 'data',
 'refers',
 'to',
 'a',
 'massive',
 'set',
 'of',
 'data',
 'that',
 'no',
 'conventional',
 'data',
 'management',
 'tool',
 'can',
 'handle.',
 'big',
 'data',
 'is',
 'therefore',
 'a',
 'concept',
 'that',
 'allows',
 'access',
 'to',
 'gigantic',
 'databases',
 'in',
 'real',
 'time.',
 'big',
 "data's",
 'main',
 'objectives',
 'are',
 'to',
 'improve',
 'a',
 "company's",
 'or',
 "system's",
 'responsiveness',
 'to',
 'a',
 'large',
 'amount',
 'of',
 'data',
 'collected,',
 'increase',
 'productivity',
 'and',
 'refine',
 'knowledge',
 'of',
 'customer',
 'behavior,',
 'so',
 'that',
 'it',
 'can',
 'offer',
 'personalized',
 'offers',
 'or',
 'advertisements',
 'and',
 'create',
 'new',
 'trends.',
 'the',
 'internet',
 'of',
 'things',
 '(iot)',
 'is',
 'a',
 'concept',
 'that',
 'connects',
 'physical',
 'or',
 'virtual',
 'objects',
 'to',
 'the',
 'internet.',
 'the',
 'technology',
 'very',
 'often',
 'used',
 'is',
 'the',
 'sensor,',
 'allowing',
 'to',
 'link',
 'a',
 'physical',
 'object',
 'such',
 'as',
 'a',
 'watch,',
 'a',
 'drone',
 'or',
 'even',
 'a',
 'speaker,',
 'to',
 'the',
 'internet.',
 'if',
 'for',
 'a',
 'long',
 'time',
 'the',
 'few',
 'objects',
 'connected',
 'to',
 'the',
 'internet',
 'were',
 'the',
 'telephone',
 'and',
 'the',
 'computer,',
 'this',
 'is',
 'no',
 'longer',
 'the',
 'case',
 'today',
 'and',
 'every',
 'year',
 'new',
 'types',
 'of',
 'objects',
 'incorporating',
 'iot',
 'technology',
 'are',
 'born.',
 'iot',
 'is',
 'one',
 'of',
 'the',
 'greatest',
 'technological',
 'revolutions',
 'of',
 'our',
 'era',
 'and',
 'its',
 'potential',
 'for',
 'exploitation',
 'is',
 'immense.',
 'iot',
 'could',
 'have',
 'a',
 'huge',
 'impact',
 'on',
 'the',
 'cars',
 'of',
 'the',
 'future',
 'or',
 'on',
 'the',
 'new',
 'versions',
 'of',
 'smart-cities,',
 'an',
 'urban',
 'space',
 'connected',
 'to',
 'the',
 'internet,',
 'thus',
 'significantly',
 'improving',
 'the',
 'lives',
 'of',
 'users,',
 'while',
 'reducing',
 'the',
 'negative',
 'impact',
 'of',
 'these',
 'on',
 'the',
 'planet.']

In [14]:
rdd3.take(5)

['big', 'data', 'refers', 'to', 'a']

In [15]:
stop=['a','to','so']

rdd3.filter(lambda x:x not in stop).collect()

['big',
 'data',
 'refers',
 'massive',
 'set',
 'of',
 'data',
 'that',
 'no',
 'conventional',
 'data',
 'management',
 'tool',
 'can',
 'handle.',
 'big',
 'data',
 'is',
 'therefore',
 'concept',
 'that',
 'allows',
 'access',
 'gigantic',
 'databases',
 'in',
 'real',
 'time.',
 'big',
 "data's",
 'main',
 'objectives',
 'are',
 'improve',
 "company's",
 'or',
 "system's",
 'responsiveness',
 'large',
 'amount',
 'of',
 'data',
 'collected,',
 'increase',
 'productivity',
 'and',
 'refine',
 'knowledge',
 'of',
 'customer',
 'behavior,',
 'that',
 'it',
 'can',
 'offer',
 'personalized',
 'offers',
 'or',
 'advertisements',
 'and',
 'create',
 'new',
 'trends.',
 'the',
 'internet',
 'of',
 'things',
 '(iot)',
 'is',
 'concept',
 'that',
 'connects',
 'physical',
 'or',
 'virtual',
 'objects',
 'the',
 'internet.',
 'the',
 'technology',
 'very',
 'often',
 'used',
 'is',
 'the',
 'sensor,',
 'allowing',
 'link',
 'physical',
 'object',
 'such',
 'as',
 'watch,',
 'drone',
 'or',
 'even',
 'speaker,',
 'the',
 'internet.',
 'if',
 'for',
 'long',
 'time',
 'the',
 'few',
 'objects',
 'connected',
 'the',
 'internet',
 'were',
 'the',
 'telephone',
 'and',
 'the',
 'computer,',
 'this',
 'is',
 'no',
 'longer',
 'the',
 'case',
 'today',
 'and',
 'every',
 'year',
 'new',
 'types',
 'of',
 'objects',
 'incorporating',
 'iot',
 'technology',
 'are',
 'born.',
 'iot',
 'is',
 'one',
 'of',
 'the',
 'greatest',
 'technological',
 'revolutions',
 'of',
 'our',
 'era',
 'and',
 'its',
 'potential',
 'for',
 'exploitation',
 'is',
 'immense.',
 'iot',
 'could',
 'have',
 'huge',
 'impact',
 'on',
 'the',
 'cars',
 'of',
 'the',
 'future',
 'or',
 'on',
 'the',
 'new',
 'versions',
 'of',
 'smart-cities,',
 'an',
 'urban',
 'space',
 'connected',
 'the',
 'internet,',
 'thus',
 'significantly',
 'improving',
 'the',
 'lives',
 'of',
 'users,',
 'while',
 'reducing',
 'the',
 'negative',
 'impact',
 'of',
 'these',
 'on',
 'the',
 'planet.']

In [16]:
rdd3.filter(lambda x: x.startswith('d')).distinct().collect()

['data', 'databases', "data's", 'drone']

In [17]:
n=spark.sparkContext.parallelize(np.arange(0,100))
n.collect()

[0,
 1,
 2,
 3,
 4,
 5,
 6,
 7,
 8,
 9,
 10,
 11,
 12,
 13,
 14,
 15,
 16,
 17,
 18,
 19,
 20,
 21,
 22,
 23,
 24,
 25,
 26,
 27,
 28,
 29,
 30,
 31,
 32,
 33,
 34,
 35,
 36,
 37,
 38,
 39,
 40,
 41,
 42,
 43,
 44,
 45,
 46,
 47,
 48,
 49,
 50,
 51,
 52,
 53,
 54,
 55,
 56,
 57,
 58,
 59,
 60,
 61,
 62,
 63,
 64,
 65,
 66,
 67,
 68,
 69,
 70,
 71,
 72,
 73,
 74,
 75,
 76,
 77,
 78,
 79,
 80,
 81,
 82,
 83,
 84,
 85,
 86,
 87,
 88,
 89,
 90,
 91,
 92,
 93,
 94,
 95,
 96,
 97,
 98,
 99]

In [18]:
n.reduce(lambda x,y:x+y)

4950

In [19]:
a=spark.sparkContext.parallelize([('a',1),('b',2)])
b=spark.sparkContext.parallelize([('a',3)])
a.join(b).collect()

[('a', (1, 3))]

In [32]:
case=spark.read.load('Case.csv',format='csv',inferSchema=True,header=True)
case.show()

+--------+--------+---------------+-----+--------------------+---------+---------+----------+
| case_id|province|           city|group|      infection_case|confirmed| latitude| longitude|
+--------+--------+---------------+-----+--------------------+---------+---------+----------+
| 1000001|   Seoul|     Yongsan-gu| true|       Itaewon Clubs|      139|37.538621|126.992652|
| 1000002|   Seoul|      Gwanak-gu| true|             Richway|      119| 37.48208|126.901384|
| 1000003|   Seoul|        Guro-gu| true| Guro-gu Call Center|       95|37.508163|126.884387|
| 1000004|   Seoul|   Yangcheon-gu| true|Yangcheon Table T...|       43|37.546061|126.874209|
| 1000005|   Seoul|      Dobong-gu| true|     Day Care Center|       43|37.679422|127.044374|
| 1000006|   Seoul|        Guro-gu| true|Manmin Central Ch...|       41|37.481059|126.894343|
| 1000007|   Seoul|from other city| true|SMR Newly Planted...|       36|        -|         -|
| 1000008|   Seoul|  Dongdaemun-gu| true|       Dongan Church|       17|37.592888|127.056766|
| 1000009|   Seoul|from other city| true|Coupang Logistics...|       25|        -|         -|
| 1000010|   Seoul|      Gwanak-gu| true|     Wangsung Church|       30|37.481735|126.930121|
| 1000011|   Seoul|   Eunpyeong-gu| true|Eunpyeong St. Mar...|       14| 37.63369|  126.9165|
| 1000012|   Seoul|   Seongdong-gu| true|    Seongdong-gu APT|       13| 37.55713|  127.0403|
| 1000013|   Seoul|      Jongno-gu| true|Jongno Community ...|       10| 37.57681|   127.006|
| 1000014|   Seoul|     Gangnam-gu| true|Samsung Medical C...|        7| 37.48825| 127.08559|
| 1000015|   Seoul|        Jung-gu| true|Jung-gu Fashion C...|        7|37.562405|126.984377|
| 1000016|   Seoul|   Seodaemun-gu| true|  Yeonana News Class|        5|37.558147|126.943799|
| 1000017|   Seoul|      Jongno-gu| true|Korea Campus Crus...|        7|37.594782|126.968022|
| 1000018|   Seoul|     Gangnam-gu| true|Gangnam Yeoksam-d...|        6|        -|         -|
| 1000019|   Seoul|from other city| true|Daejeon door-to-d...|        1|        -|         -|
| 1000020|   Seoul|   Geumcheon-gu| true|Geumcheon-gu rice...|        6|        -|         -|
+--------+--------+---------------+-----+--------------------+---------+---------+----------+
only showing top 20 rows

In [33]:
case=case.select('province','city','confirmed')
case.show()

+--------+---------------+---------+
|province|           city|confirmed|
+--------+---------------+---------+
|   Seoul|     Yongsan-gu|      139|
|   Seoul|      Gwanak-gu|      119|
|   Seoul|        Guro-gu|       95|
|   Seoul|   Yangcheon-gu|       43|
|   Seoul|      Dobong-gu|       43|
|   Seoul|        Guro-gu|       41|
|   Seoul|from other city|       36|
|   Seoul|  Dongdaemun-gu|       17|
|   Seoul|from other city|       25|
|   Seoul|      Gwanak-gu|       30|
|   Seoul|   Eunpyeong-gu|       14|
|   Seoul|   Seongdong-gu|       13|
|   Seoul|      Jongno-gu|       10|
|   Seoul|     Gangnam-gu|        7|
|   Seoul|        Jung-gu|        7|
|   Seoul|   Seodaemun-gu|        5|
|   Seoul|      Jongno-gu|        7|
|   Seoul|     Gangnam-gu|        6|
|   Seoul|from other city|        1|
|   Seoul|   Geumcheon-gu|        6|
+--------+---------------+---------+
only showing top 20 rows

In [30]:
case.sort('confirmed').show()

Py4JJavaError: An error occurred while calling o238.showString.
: java.lang.UnsupportedOperationException: Cannot generate code for expression: input[2, int, true] DESC NULLS LAST
	at org.apache.spark.sql.errors.QueryExecutionErrors$.cannotGenerateCodeForExpressionError(QueryExecutionErrors.scala:83)
	at org.apache.spark.sql.catalyst.expressions.Unevaluable.doGenCode(Expression.scala:312)
	at org.apache.spark.sql.catalyst.expressions.Unevaluable.doGenCode$(Expression.scala:311)
	at org.apache.spark.sql.catalyst.expressions.SortOrder.doGenCode(SortOrder.scala:62)
	at org.apache.spark.sql.catalyst.expressions.Expression.$anonfun$genCode$3(Expression.scala:151)
	at scala.Option.getOrElse(Option.scala:189)
	at org.apache.spark.sql.catalyst.expressions.Expression.genCode(Expression.scala:146)
	at org.apache.spark.sql.catalyst.expressions.Alias.genCode(namedExpressions.scala:171)
	at org.apache.spark.sql.execution.ProjectExec.$anonfun$doConsume$2(basicPhysicalOperators.scala:73)
	at scala.collection.TraversableLike.$anonfun$map$1(TraversableLike.scala:286)
	at scala.collection.mutable.ResizableArray.foreach(ResizableArray.scala:62)
	at scala.collection.mutable.ResizableArray.foreach$(ResizableArray.scala:55)
	at scala.collection.mutable.ArrayBuffer.foreach(ArrayBuffer.scala:49)
	at scala.collection.TraversableLike.map(TraversableLike.scala:286)
	at scala.collection.TraversableLike.map$(TraversableLike.scala:279)
	at scala.collection.AbstractTraversable.map(Traversable.scala:108)
	at org.apache.spark.sql.execution.ProjectExec.$anonfun$doConsume$1(basicPhysicalOperators.scala:73)
	at org.apache.spark.sql.catalyst.expressions.codegen.CodegenContext.withSubExprEliminationExprs(CodeGenerator.scala:1039)
	at org.apache.spark.sql.execution.ProjectExec.doConsume(basicPhysicalOperators.scala:73)
	at org.apache.spark.sql.execution.CodegenSupport.consume(WholeStageCodegenExec.scala:195)
	at org.apache.spark.sql.execution.CodegenSupport.consume$(WholeStageCodegenExec.scala:150)
	at org.apache.spark.sql.execution.InputAdapter.consume(WholeStageCodegenExec.scala:497)
	at org.apache.spark.sql.execution.InputRDDCodegen.doProduce(WholeStageCodegenExec.scala:484)
	at org.apache.spark.sql.execution.InputRDDCodegen.doProduce$(WholeStageCodegenExec.scala:457)
	at org.apache.spark.sql.execution.InputAdapter.doProduce(WholeStageCodegenExec.scala:497)
	at org.apache.spark.sql.execution.CodegenSupport.$anonfun$produce$1(WholeStageCodegenExec.scala:96)
	at org.apache.spark.sql.execution.SparkPlan.$anonfun$executeQuery$1(SparkPlan.scala:222)
	at org.apache.spark.rdd.RDDOperationScope$.withScope(RDDOperationScope.scala:151)
	at org.apache.spark.sql.execution.SparkPlan.executeQuery(SparkPlan.scala:219)
	at org.apache.spark.sql.execution.CodegenSupport.produce(WholeStageCodegenExec.scala:91)
	at org.apache.spark.sql.execution.CodegenSupport.produce$(WholeStageCodegenExec.scala:91)
	at org.apache.spark.sql.execution.InputAdapter.produce(WholeStageCodegenExec.scala:497)
	at org.apache.spark.sql.execution.ProjectExec.doProduce(basicPhysicalOperators.scala:54)
	at org.apache.spark.sql.execution.CodegenSupport.$anonfun$produce$1(WholeStageCodegenExec.scala:96)
	at org.apache.spark.sql.execution.SparkPlan.$anonfun$executeQuery$1(SparkPlan.scala:222)
	at org.apache.spark.rdd.RDDOperationScope$.withScope(RDDOperationScope.scala:151)
	at org.apache.spark.sql.execution.SparkPlan.executeQuery(SparkPlan.scala:219)
	at org.apache.spark.sql.execution.CodegenSupport.produce(WholeStageCodegenExec.scala:91)
	at org.apache.spark.sql.execution.CodegenSupport.produce$(WholeStageCodegenExec.scala:91)
	at org.apache.spark.sql.execution.ProjectExec.produce(basicPhysicalOperators.scala:41)
	at org.apache.spark.sql.execution.WholeStageCodegenExec.doCodeGen(WholeStageCodegenExec.scala:659)
	at org.apache.spark.sql.execution.WholeStageCodegenExec.doExecute(WholeStageCodegenExec.scala:722)
	at org.apache.spark.sql.execution.SparkPlan.$anonfun$execute$1(SparkPlan.scala:184)
	at org.apache.spark.sql.execution.SparkPlan.$anonfun$executeQuery$1(SparkPlan.scala:222)
	at org.apache.spark.rdd.RDDOperationScope$.withScope(RDDOperationScope.scala:151)
	at org.apache.spark.sql.execution.SparkPlan.executeQuery(SparkPlan.scala:219)
	at org.apache.spark.sql.execution.SparkPlan.execute(SparkPlan.scala:180)
	at org.apache.spark.sql.execution.TakeOrderedAndProjectExec.executeCollect(limit.scala:204)
	at org.apache.spark.sql.Dataset.collectFromPlan(Dataset.scala:3715)
	at org.apache.spark.sql.Dataset.$anonfun$head$1(Dataset.scala:2728)
	at org.apache.spark.sql.Dataset.$anonfun$withAction$1(Dataset.scala:3706)
	at org.apache.spark.sql.execution.SQLExecution$.$anonfun$withNewExecutionId$5(SQLExecution.scala:103)
	at org.apache.spark.sql.execution.SQLExecution$.withSQLConfPropagated(SQLExecution.scala:163)
	at org.apache.spark.sql.execution.SQLExecution$.$anonfun$withNewExecutionId$1(SQLExecution.scala:90)
	at org.apache.spark.sql.SparkSession.withActive(SparkSession.scala:775)
	at org.apache.spark.sql.execution.SQLExecution$.withNewExecutionId(SQLExecution.scala:64)
	at org.apache.spark.sql.Dataset.withAction(Dataset.scala:3704)
	at org.apache.spark.sql.Dataset.head(Dataset.scala:2728)
	at org.apache.spark.sql.Dataset.take(Dataset.scala:2935)
	at org.apache.spark.sql.Dataset.getRows(Dataset.scala:287)
	at org.apache.spark.sql.Dataset.showString(Dataset.scala:326)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at py4j.reflection.MethodInvoker.invoke(MethodInvoker.java:244)
	at py4j.reflection.ReflectionEngine.invoke(ReflectionEngine.java:357)
	at py4j.Gateway.invoke(Gateway.java:282)
	at py4j.commands.AbstractCommand.invokeMethod(AbstractCommand.java:132)
	at py4j.commands.CallCommand.execute(CallCommand.java:79)
	at py4j.ClientServerConnection.waitForCommands(ClientServerConnection.java:182)
	at py4j.ClientServerConnection.run(ClientServerConnection.java:106)
	at java.lang.Thread.run(Thread.java:750)

In [34]:
from pyspark.sql import functions as F

In [35]:
case.sort('confirmed').show()

+-----------------+---------------+---------+
|         province|           city|confirmed|
+-----------------+---------------+---------+
|          Jeju-do|              -|        0|
|       Gangwon-do|              -|        0|
|            Seoul|     Gangseo-gu|        0|
|            Busan|from other city|        1|
|     Jeollabuk-do|from other city|        1|
|            Seoul|from other city|        1|
|            Seoul|     Gangnam-gu|        1|
|           Sejong|from other city|        1|
|     Jeollanam-do|from other city|        1|
|          Jeju-do|from other city|        1|
|            Seoul|from other city|        1|
|            Seoul|              -|        1|
|           Sejong|              -|        1|
|          Gwangju|              -|        1|
|            Daegu|from other city|        2|
|            Daegu|from other city|        2|
|          Incheon|from other city|        2|
|            Seoul|from other city|        2|
|          Daejeon|from other city|        2|
|Chungcheongbuk-do|from other city|        2|
+-----------------+---------------+---------+
only showing top 20 rows

In [36]:
case.sort(F.desc('confirmed')).show()

+-----------------+---------------+---------+
|         province|           city|confirmed|
+-----------------+---------------+---------+
|            Daegu|         Nam-gu|     4511|
|            Daegu|              -|      917|
|            Daegu|              -|      747|
| Gyeongsangbuk-do|from other city|      566|
|      Gyeonggi-do|              -|      305|
|            Seoul|              -|      298|
|            Daegu|   Dalseong-gun|      196|
| Gyeongsangbuk-do|              -|      190|
|            Seoul|              -|      162|
|            Seoul|     Yongsan-gu|      139|
| Gyeongsangbuk-do|              -|      133|
|            Daegu|         Seo-gu|      124|
|            Seoul|      Gwanak-gu|      119|
| Gyeongsangbuk-do|   Cheongdo-gun|      119|
|Chungcheongnam-do|     Cheonan-si|      103|
|            Daegu|   Dalseong-gun|      101|
|            Seoul|              -|      100|
|            Seoul|        Guro-gu|       95|
|      Gyeonggi-do|              -|       84|
|          Incheon|              -|       68|
+-----------------+---------------+---------+
only showing top 20 rows

In [37]:
from pyspark.sql.types import *

In [38]:
case=case.withColumn('confirmed',F.col('confirmed').cast(IntegerType()))
case.show()

+--------+---------------+---------+
|province|           city|confirmed|
+--------+---------------+---------+
|   Seoul|     Yongsan-gu|      139|
|   Seoul|      Gwanak-gu|      119|
|   Seoul|        Guro-gu|       95|
|   Seoul|   Yangcheon-gu|       43|
|   Seoul|      Dobong-gu|       43|
|   Seoul|        Guro-gu|       41|
|   Seoul|from other city|       36|
|   Seoul|  Dongdaemun-gu|       17|
|   Seoul|from other city|       25|
|   Seoul|      Gwanak-gu|       30|
|   Seoul|   Eunpyeong-gu|       14|
|   Seoul|   Seongdong-gu|       13|
|   Seoul|      Jongno-gu|       10|
|   Seoul|     Gangnam-gu|        7|
|   Seoul|        Jung-gu|        7|
|   Seoul|   Seodaemun-gu|        5|
|   Seoul|      Jongno-gu|        7|
|   Seoul|     Gangnam-gu|        6|
|   Seoul|from other city|        1|
|   Seoul|   Geumcheon-gu|        6|
+--------+---------------+---------+
only showing top 20 rows

In [40]:
case.printSchema()

root
 |-- province: string (nullable = true)
 |-- city: string (nullable = true)
 |-- confirmed: integer (nullable = true)

In [44]:
case.filter((case.confirmed<100) & (case.city=='Gangnam-gu')).show()

+--------+----------+---------+
|province|      city|confirmed|
+--------+----------+---------+
|   Seoul|Gangnam-gu|        7|
|   Seoul|Gangnam-gu|        6|
|   Seoul|Gangnam-gu|        1|
|   Seoul|Gangnam-gu|        4|
+--------+----------+---------+

In [45]:
case.groupBy(['province','city']).agg(F.sum('confirmed').alias('SUm')).show()

+----------------+---------------+----+
|        province|           city| SUm|
+----------------+---------------+----+
|Gyeongsangnam-do|       Jinju-si|   9|
|           Seoul|        Guro-gu| 139|
|           Seoul|     Gangnam-gu|  18|
|         Daejeon|              -| 100|
|    Jeollabuk-do|from other city|   6|
|Gyeongsangnam-do|Changnyeong-gun|   7|
|           Seoul|              -| 561|
|         Jeju-do|from other city|   1|
|Gyeongsangbuk-do|              -| 345|
|Gyeongsangnam-do|   Geochang-gun|  18|
|Gyeongsangbuk-do|        Gumi-si|  10|
|         Incheon|from other city| 117|
|           Busan|              -|  85|
|           Daegu|         Seo-gu| 124|
|           Busan|     Suyeong-gu|   5|
|     Gyeonggi-do|   Uijeongbu-si|  50|
|           Seoul|     Yongsan-gu| 139|
|           Daegu|              -|1705|
|           Seoul|   Seodaemun-gu|   5|
|     Gyeonggi-do|    Seongnam-si|  94|
+----------------+---------------+----+
only showing top 20 rows

In [46]:
region=spark.read.load('Region.csv',format='csv',inferSchema=True,header=True)
region.show()

+-----+--------+-------------+---------+----------+-----------------------+------------------+----------------+-------------+------------------------+-------------------+------------------+
| code|province|         city| latitude| longitude|elementary_school_count|kindergarten_count|university_count|academy_ratio|elderly_population_ratio|elderly_alone_ratio|nursing_home_count|
+-----+--------+-------------+---------+----------+-----------------------+------------------+----------------+-------------+------------------------+-------------------+------------------+
|10000|   Seoul|        Seoul|37.566953|126.977977|                    607|               830|              48|         1.44|                   15.38|                5.8|             22739|
|10010|   Seoul|   Gangnam-gu|37.518421|127.047222|                     33|                38|               0|         4.18|                   13.17|                4.3|              3088|
|10020|   Seoul|  Gangdong-gu|37.530492|127.123837|                     27|                32|               0|         1.54|                   14.55|                5.4|              1023|
|10030|   Seoul|   Gangbuk-gu|37.639938|127.025508|                     14|                21|               0|         0.67|                   19.49|                8.5|               628|
|10040|   Seoul|   Gangseo-gu|37.551166|126.849506|                     36|                56|               1|         1.17|                   14.39|                5.7|              1080|
|10050|   Seoul|    Gwanak-gu| 37.47829|126.951502|                     22|                33|               1|         0.89|                   15.12|                4.9|               909|
|10060|   Seoul|  Gwangjin-gu|37.538712|127.082366|                     22|                33|               3|         1.16|                   13.75|                4.8|               723|
|10070|   Seoul|      Guro-gu|37.495632| 126.88765|                     26|                34|               3|          1.0|                   16.21|                5.7|               741|
|10080|   Seoul| Geumcheon-gu|37.456852|126.895229|                     18|                19|               0|         0.96|                   16.15|                6.7|               475|
|10090|   Seoul|     Nowon-gu|37.654259|127.056294|                     42|                66|               6|         1.39|                    15.4|                7.4|               952|
|10100|   Seoul|    Dobong-gu|37.668952|127.047082|                     23|                26|               1|         0.95|                   17.89|                7.2|               485|
|10110|   Seoul|Dongdaemun-gu|37.574552|127.039721|                     21|                31|               4|         1.06|                   17.26|                6.7|               832|
|10120|   Seoul|   Dongjak-gu|37.510571|126.963604|                     21|                34|               3|         1.17|                   15.85|                5.2|               762|
|10130|   Seoul|      Mapo-gu|37.566283|126.901644|                     22|                24|               2|         1.83|                   14.05|                4.9|               929|
|10140|   Seoul| Seodaemun-gu|37.579428|126.936771|                     19|                25|               6|         1.12|                   16.77|                6.2|               587|
|10150|   Seoul|    Seocho-gu|37.483804|127.032693|                     24|                27|               1|          2.6|                   13.39|                3.8|              1465|
|10160|   Seoul| Seongdong-gu|37.563277|127.036647|                     21|                30|               2|         0.97|                   14.76|                5.3|               593|
|10170|   Seoul|  Seongbuk-gu|37.589562|  127.0167|                     29|                49|               6|         1.02|                   16.15|                6.0|               729|
|10180|   Seoul|    Songpa-gu| 37.51462|127.106141|                     40|                51|               1|         1.65|                    13.1|                4.1|              1527|
|10190|   Seoul| Yangcheon-gu|37.517189|126.866618|                     30|                43|               0|         2.26|                   13.55|                5.5|               816|
+-----+--------+-------------+---------+----------+-----------------------+------------------+----------------+-------------+------------------------+-------------------+------------------+
only showing top 20 rows

In [47]:
case.join(region,['province','city'],how='left').show()

+--------+---------------+---------+-----+---------+----------+-----------------------+------------------+----------------+-------------+------------------------+-------------------+------------------+
|province|           city|confirmed| code| latitude| longitude|elementary_school_count|kindergarten_count|university_count|academy_ratio|elderly_population_ratio|elderly_alone_ratio|nursing_home_count|
+--------+---------------+---------+-----+---------+----------+-----------------------+------------------+----------------+-------------+------------------------+-------------------+------------------+
|   Seoul|     Yongsan-gu|      139|10210|37.532768|126.990021|                     15|                13|               1|         0.68|                   16.87|                6.5|               435|
|   Seoul|      Gwanak-gu|      119|10050| 37.47829|126.951502|                     22|                33|               1|         0.89|                   15.12|                4.9|               909|
|   Seoul|        Guro-gu|       95|10070|37.495632| 126.88765|                     26|                34|               3|          1.0|                   16.21|                5.7|               741|
|   Seoul|   Yangcheon-gu|       43|10190|37.517189|126.866618|                     30|                43|               0|         2.26|                   13.55|                5.5|               816|
|   Seoul|      Dobong-gu|       43|10100|37.668952|127.047082|                     23|                26|               1|         0.95|                   17.89|                7.2|               485|
|   Seoul|        Guro-gu|       41|10070|37.495632| 126.88765|                     26|                34|               3|          1.0|                   16.21|                5.7|               741|
|   Seoul|from other city|       36| null|     null|      null|                   null|              null|            null|         null|                    null|               null|              null|
|   Seoul|  Dongdaemun-gu|       17|10110|37.574552|127.039721|                     21|                31|               4|         1.06|                   17.26|                6.7|               832|
|   Seoul|from other city|       25| null|     null|      null|                   null|              null|            null|         null|                    null|               null|              null|
|   Seoul|      Gwanak-gu|       30|10050| 37.47829|126.951502|                     22|                33|               1|         0.89|                   15.12|                4.9|               909|
|   Seoul|   Eunpyeong-gu|       14|10220|37.603481|126.929173|                     31|                44|               1|         1.09|                    17.0|                6.5|               874|
|   Seoul|   Seongdong-gu|       13|10160|37.563277|127.036647|                     21|                30|               2|         0.97|                   14.76|                5.3|               593|
|   Seoul|      Jongno-gu|       10|10230|37.572999|126.979189|                     13|                17|               3|         1.71|                   18.27|                6.8|               668|
|   Seoul|     Gangnam-gu|        7|10010|37.518421|127.047222|                     33|                38|               0|         4.18|                   13.17|                4.3|              3088|
|   Seoul|        Jung-gu|        7|10240|37.563988| 126.99753|                     12|                14|               2|         0.94|                   18.42|                7.4|               728|
|   Seoul|   Seodaemun-gu|        5|10140|37.579428|126.936771|                     19|                25|               6|         1.12|                   16.77|                6.2|               587|
|   Seoul|      Jongno-gu|        7|10230|37.572999|126.979189|                     13|                17|               3|         1.71|                   18.27|                6.8|               668|
|   Seoul|     Gangnam-gu|        6|10010|37.518421|127.047222|                     33|                38|               0|         4.18|                   13.17|                4.3|              3088|
|   Seoul|from other city|        1| null|     null|      null|                   null|              null|            null|         null|                    null|               null|              null|
|   Seoul|   Geumcheon-gu|        6|10080|37.456852|126.895229|                     18|                19|               0|         0.96|                   16.15|                6.7|               475|
+--------+---------------+---------+-----+---------+----------+-----------------------+------------------+----------------+-------------+------------------------+-------------------+------------------+
only showing top 20 rows

In [48]:
time=spark.read.load('TimeProvince.csv',inferSchema=True,header=True,format='csv')

In [49]:
time.show()

+----------+----+-----------------+---------+--------+--------+
|      date|time|         province|confirmed|released|deceased|
+----------+----+-----------------+---------+--------+--------+
|2020-01-20|  16|            Seoul|        0|       0|       0|
|2020-01-20|  16|            Busan|        0|       0|       0|
|2020-01-20|  16|            Daegu|        0|       0|       0|
|2020-01-20|  16|          Incheon|        1|       0|       0|
|2020-01-20|  16|          Gwangju|        0|       0|       0|
|2020-01-20|  16|          Daejeon|        0|       0|       0|
|2020-01-20|  16|            Ulsan|        0|       0|       0|
|2020-01-20|  16|           Sejong|        0|       0|       0|
|2020-01-20|  16|      Gyeonggi-do|        0|       0|       0|
|2020-01-20|  16|       Gangwon-do|        0|       0|       0|
|2020-01-20|  16|Chungcheongbuk-do|        0|       0|       0|
|2020-01-20|  16|Chungcheongnam-do|        0|       0|       0|
|2020-01-20|  16|     Jeollabuk-do|        0|       0|       0|
|2020-01-20|  16|     Jeollanam-do|        0|       0|       0|
|2020-01-20|  16| Gyeongsangbuk-do|        0|       0|       0|
|2020-01-20|  16| Gyeongsangnam-do|        0|       0|       0|
|2020-01-20|  16|          Jeju-do|        0|       0|       0|
|2020-01-21|  16|            Seoul|        0|       0|       0|
|2020-01-21|  16|            Busan|        0|       0|       0|
|2020-01-21|  16|            Daegu|        0|       0|       0|
+----------+----+-----------------+---------+--------+--------+
only showing top 20 rows

In [51]:
from pyspark.sql.window import Window

In [53]:
window_f=Window.partitionBy('province').orderBy('date')

In [54]:
time=time.withColumn('Lag',F.lag('confirmed',7).over(window_f))
time.show()

+----------+----+--------+---------+--------+--------+----+
|      date|time|province|confirmed|released|deceased| Lag|
+----------+----+--------+---------+--------+--------+----+
|2020-01-20|  16|   Busan|        0|       0|       0|null|
|2020-01-21|  16|   Busan|        0|       0|       0|null|
|2020-01-22|  16|   Busan|        0|       0|       0|null|
|2020-01-23|  16|   Busan|        0|       0|       0|null|
|2020-01-24|  16|   Busan|        0|       0|       0|null|
|2020-01-25|  16|   Busan|        0|       0|       0|null|
|2020-01-26|  16|   Busan|        0|       0|       0|null|
|2020-01-27|  16|   Busan|        0|       0|       0|   0|
|2020-01-28|  16|   Busan|        0|       0|       0|   0|
|2020-01-29|  16|   Busan|        0|       0|       0|   0|
|2020-01-30|  16|   Busan|        0|       0|       0|   0|
|2020-01-31|  16|   Busan|        0|       0|       0|   0|
|2020-02-01|  16|   Busan|        0|       0|       0|   0|
|2020-02-02|  16|   Busan|        0|       0|       0|   0|
|2020-02-03|  16|   Busan|        0|       0|       0|   0|
|2020-02-04|  16|   Busan|        0|       0|       0|   0|
|2020-02-05|  16|   Busan|        0|       0|       0|   0|
|2020-02-06|  16|   Busan|        0|       0|       0|   0|
|2020-02-07|  16|   Busan|        0|       0|       0|   0|
|2020-02-08|  16|   Busan|        0|       0|       0|   0|
+----------+----+--------+---------+--------+--------+----+
only showing top 20 rows

In [55]:
case.show()

+--------+---------------+---------+
|province|           city|confirmed|
+--------+---------------+---------+
|   Seoul|     Yongsan-gu|      139|
|   Seoul|      Gwanak-gu|      119|
|   Seoul|        Guro-gu|       95|
|   Seoul|   Yangcheon-gu|       43|
|   Seoul|      Dobong-gu|       43|
|   Seoul|        Guro-gu|       41|
|   Seoul|from other city|       36|
|   Seoul|  Dongdaemun-gu|       17|
|   Seoul|from other city|       25|
|   Seoul|      Gwanak-gu|       30|
|   Seoul|   Eunpyeong-gu|       14|
|   Seoul|   Seongdong-gu|       13|
|   Seoul|      Jongno-gu|       10|
|   Seoul|     Gangnam-gu|        7|
|   Seoul|        Jung-gu|        7|
|   Seoul|   Seodaemun-gu|        5|
|   Seoul|      Jongno-gu|        7|
|   Seoul|     Gangnam-gu|        6|
|   Seoul|from other city|        1|
|   Seoul|   Geumcheon-gu|        6|
+--------+---------------+---------+
only showing top 20 rows

In [56]:
case.limit(10).toPandas()

  province             city  confirmed
0    Seoul       Yongsan-gu        139
1    Seoul        Gwanak-gu        119
2    Seoul          Guro-gu         95
3    Seoul     Yangcheon-gu         43
4    Seoul        Dobong-gu         43
5    Seoul          Guro-gu         41
6    Seoul  from other city         36
7    Seoul    Dongdaemun-gu         17
8    Seoul  from other city         25
9    Seoul        Gwanak-gu         30

In [58]:
def high_low(conf):
    if conf>=50:
        return 'High'
    return 'low'

high_low=F.udf(high_low,StringType())

case=case.withColumn('HighLow',high_low(F.col('confirmed')))
case.show()

+--------+---------------+---------+-------+
|province|           city|confirmed|HighLow|
+--------+---------------+---------+-------+
|   Seoul|     Yongsan-gu|      139|   High|
|   Seoul|      Gwanak-gu|      119|   High|
|   Seoul|        Guro-gu|       95|   High|
|   Seoul|   Yangcheon-gu|       43|    low|
|   Seoul|      Dobong-gu|       43|    low|
|   Seoul|        Guro-gu|       41|    low|
|   Seoul|from other city|       36|    low|
|   Seoul|  Dongdaemun-gu|       17|    low|
|   Seoul|from other city|       25|    low|
|   Seoul|      Gwanak-gu|       30|    low|
|   Seoul|   Eunpyeong-gu|       14|    low|
|   Seoul|   Seongdong-gu|       13|    low|
|   Seoul|      Jongno-gu|       10|    low|
|   Seoul|     Gangnam-gu|        7|    low|
|   Seoul|        Jung-gu|        7|    low|
|   Seoul|   Seodaemun-gu|        5|    low|
|   Seoul|      Jongno-gu|        7|    low|
|   Seoul|     Gangnam-gu|        6|    low|
|   Seoul|from other city|        1|    low|
|   Seoul|   Geumcheon-gu|        6|    low|
+--------+---------------+---------+-------+
only showing top 20 rows

In [59]:
text=spark.sparkContext.textFile('lab3.txt')
text.collect()

["Big Data refers to a massive set of data that no conventional data management tool can handle. Big Data is therefore a concept that allows access to gigantic databases in real time. Big Data's main objectives are to improve a company's or system's responsiveness to a large amount of data collected, increase productivity and refine knowledge of customer behavior, so that it can offer personalized offers or advertisements and create new trends.",
 'The Internet of Things (IoT) is a concept that connects physical or virtual objects to the internet. The technology very often used is the sensor, allowing to link a physical object such as a watch, a drone or even a speaker, to the internet. If for a long time the few objects connected to the Internet were the telephone and the computer, this is no longer the case today and every year new types of objects incorporating IOT technology are born. IOT is one of the greatest technological revolutions of our era and its potential for exploitation is immense. IOT could have a huge impact on the cars of the future or on the new versions of smart-cities, an urban space connected to the Internet, thus significantly improving the lives of users, while reducing the negative impact of these on the planet. ']

In [61]:
text.flatMap(lambda x:x.split()).map(lambda x: (x,1)).reduceByKey(lambda x,y:x+y).collect()

[('refers', 1),
 ('massive', 1),
 ('set', 1),
 ('of', 11),
 ('no', 2),
 ('conventional', 1),
 ('management', 1),
 ('is', 6),
 ('in', 1),
 ("Data's", 1),
 ('objectives', 1),
 ('are', 2),
 ('improve', 1),
 ("company's", 1),
 ("system's", 1),
 ('large', 1),
 ('amount', 1),
 ('collected,', 1),
 ('increase', 1),
 ('knowledge', 1),
 ('customer', 1),
 ('personalized', 1),
 ('offers', 1),
 ('new', 3),
 ('The', 2),
 ('Things', 1),
 ('(IoT)', 1),
 ('connects', 1),
 ('internet.', 2),
 ('technology', 2),
 ('very', 1),
 ('used', 1),
 ('sensor,', 1),
 ('allowing', 1),
 ('as', 1),
 ('watch,', 1),
 ('even', 1),
 ('speaker,', 1),
 ('long', 1),
 ('telephone', 1),
 ('computer,', 1),
 ('this', 1),
 ('longer', 1),
 ('year', 1),
 ('incorporating', 1),
 ('IOT', 3),
 ('born.', 1),
 ('greatest', 1),
 ('potential', 1),
 ('exploitation', 1),
 ('have', 1),
 ('huge', 1),
 ('versions', 1),
 ('an', 1),
 ('space', 1),
 ('Internet,', 1),
 ('thus', 1),
 ('significantly', 1),
 ('reducing', 1),
 ('negative', 1),
 ('these', 1),
 ('planet.', 1),
 ('Big', 3),
 ('Data', 2),
 ('to', 9),
 ('a', 11),
 ('data', 3),
 ('that', 4),
 ('tool', 1),
 ('can', 2),
 ('handle.', 1),
 ('therefore', 1),
 ('concept', 2),
 ('allows', 1),
 ('access', 1),
 ('gigantic', 1),
 ('databases', 1),
 ('real', 1),
 ('time.', 1),
 ('main', 1),
 ('or', 5),
 ('responsiveness', 1),
 ('productivity', 1),
 ('and', 5),
 ('refine', 1),
 ('behavior,', 1),
 ('so', 1),
 ('it', 1),
 ('offer', 1),
 ('advertisements', 1),
 ('create', 1),
 ('trends.', 1),
 ('Internet', 2),
 ('physical', 2),
 ('virtual', 1),
 ('objects', 3),
 ('the', 16),
 ('often', 1),
 ('link', 1),
 ('object', 1),
 ('such', 1),
 ('drone', 1),
 ('If', 1),
 ('for', 2),
 ('time', 1),
 ('few', 1),
 ('connected', 2),
 ('were', 1),
 ('case', 1),
 ('today', 1),
 ('every', 1),
 ('types', 1),
 ('one', 1),
 ('technological', 1),
 ('revolutions', 1),
 ('our', 1),
 ('era', 1),
 ('its', 1),
 ('immense.', 1),
 ('could', 1),
 ('impact', 2),
 ('on', 3),
 ('cars', 1),
 ('future', 1),
 ('smart-cities,', 1),
 ('urban', 1),
 ('improving', 1),
 ('lives', 1),
 ('users,', 1),
 ('while', 1)]